### ISSUE TITLE
updatebatch!() for statistics that benefit from batch updates

### ISSUE THREAD

**Issue by joshday** [joshday/OnlineStats.jl#10]
Some statistics will be much faster in batch updates instead of singletons.  I think we should be explicit in how the update is performed (also because updating by singletons is not equivalent to updating by batch unless it uses `EqualWeighting`).

What is preferred here for batch `y`?
- `updatebatch!(o, y)`
- `update!(o, y, batch::Bool = false)`

**Comment by tbreloff** [comment]
I *think* I slightly prefer the second, but with a semicolon: `update!(o, y; batch::Bool = false)`
This way it doesn't have to compile multiple versions of the function, and we can potentially add other settings in the future in a clean way.  But.. I don't have a strong opinion about it right now.

**Comment by joshday** [comment]
Sounds good to me.

**Comment by tbreloff** [comment]
How do weightings factor into this?  For example you can't batch-update (i.e. take a weighted avg of previousMean and mean(y)) with an exponential weighting because each new observation would have a different weight.  I guess we have to throw errors if we ask for a batch update but it's not a correct thing to do?  Or warn?  Or silently fall back to the singleton updates?

**Comment by joshday** [comment]
In the batch update, wouldn't everything in the new batch have equal weight with this?

```julia
λ = weight(obj, length(y))
smooth(previousMean, mean(y), λ)
```

**Comment by tbreloff** [comment]
that's my point... it wouldn't be correct to weight the whole batch as if it's one observation in the exponential case

**Comment by joshday** [comment]
Okay, right.  This is only for when you want the whole batch treated as one equal piece of information.  If you want every observation weighted exponentially, you need `batch = false` method.  

Not everything needs a batch update method.  I'm thinking the application of this is geared more toward stochastic gradient descent, online EM, online MM, etc., where you get faster convergence using batches.

**Comment by tbreloff** [comment]
Based on that comment, maybe it'll be cleaner to have a separate function `batchupdate!()` that is explicit and can do error checking for incompatible weightings, etc?

**Comment by joshday** [comment]
Agreed, I think `batchupdate!()` is the way to go.

**Comment by joshday** [comment]
Just to put this on record, the function name I've been using is `updatebatch!`
