### ISSUE TITLE
Pearson correlation between two vectors cor(x,y)

### ISSUE THREAD

**Issue by ivborissov** [joshday/OnlineStats.jl#100]
Hi,
I am interested in online algorithm to compute correlation between two vectors like `Base.cor(x,y)`. 
Do you have it implemented (sorry if I missed it in the doc)?

**Comment by joshday** [comment]
No problem!  You can get the entire correlation matrix with `CovMatrix`:

```julia
xy = randn(1000, 2)
o = CovMatrix(2)
Series(xy, o)
cor(o)
```

**Comment by ivborissov** [comment]
I see, thanks!
