### ISSUE TITLE
MVs or Groups for Correlations

### ISSUE THREAD

**Issue by ivborissov** [joshday/OnlineStats.jl#101]
Hi, sorry if it partly duplicates the closed issue
https://github.com/joshday/OnlineStats.jl/issues/100

I am in doubt  if there is more efficient way to compute Pearson coefficients:
I have `n` measurements for components of two vectors and I want to compute correlations between every two components. In "static" version I have the following code, which outputs exactly what I need:
```
n=100
x = [rand(n), rand(n)]
y = [rand(n), rand(n), rand(n)]
cor.(x,transpose.(y)')

2×3 Array{Float64,2}:
  0.10904    -0.0272274  -0.0403086
 -0.0423529   0.0366858   0.134013 
```
With online algorithm I am computing `CovMatrix()`  :

```
using OnlineStats
o = CovMatrix(length(x)+length(y))
s = Series(hcat(vcat(x,y)...), o)
c = cor(o)

5×5 Array{Float64,2}:
  1.0         0.0386963   0.10904     -0.0272274  -0.0403086 
  0.0386963   1.0        -0.0423529    0.0366858   0.134013  
  0.10904    -0.0423529   1.0          0.0230301  -0.00348462
 -0.0272274   0.0366858   0.0230301    1.0        -0.0895397 
 -0.0403086   0.134013   -0.00348462  -0.0895397   1.0  


c[1:length(x),length(y):end]

2×3 Array{Float64,2}:
  0.10904    -0.0272274  -0.0403086
 -0.0423529   0.0366858   0.134013 
```
However when `lenght(x), length(y)` is growing the code becomes computationally expensive because the algorithm computes matrix of `lenght(x) + length(y)` * `lenght(x) + length(y)`. Do you have an idea how can it be optimized? I thought it may be better to have small matrixes for each 2 vectors united into `Group` or a special method for single Pearson coefficient

**Comment by joshday** [comment]
There are probably ways to optimize only returning specific elements of the covariance matrix, but I'm not sure there's big gains to be had:

```
julia> x = randn(10^6, 50);

julia> @time Series(x, CovMatrix(50));
  0.783656 seconds (1.00 M allocations: 30.577 MiB, 4.19% gc time)
```

If you make a `CovMatrix(2)` for every pair of vectors (I think that's what you're suggesting) then you would end up making a lot of the same calculations twice.

**Comment by ivborissov** [comment]
Thanks! Yes `@time` proved that computing the whole matrix works better than `CovMatrix(2)` for every pair of vectors. Not sure if adding the `(Vector,Vector)->Float64` method would boost the computations. So it is not an issue but more like a question for discussion )
