### ISSUE TITLE
FitCategorical

### ISSUE THREAD

**Issue by HamletFr** [joshday/OnlineStats.jl#102]
In the talk at the PyData NYC last december you showed the following two plots?

```
@time s = reduce(FitCategorical(Int64), db; select = :passenger_count)
plot(s, xlab = "Number of Passengers")
```
and
```
@time s = reduce(2 * OHistogram(0:.5:60), db; 
    select = (:fare_amount, :tip_amount))
plot(s, label = [:Fare :Tip], xlab = :Amount, title = "Fare and Tips")
```
Are both commands depreceated?

**Comment by joshday** [comment]
Yes!  The deprecation cycle was short.  

- `FitCategorical` is now `CountMap`
-  Both `OHistogram` and `IHistogram` are now just `Hist` and a different algorithm is used depending on if you provide a `Range` (fixed bins) or an `Int` (adaptive bins)

**Comment by joshday** [comment]
The above examples should now be

```julia
reduce(CountMap(Int), db; select = :passenger_count)
```

and

```julia
reduce(2Hist(0:.5:60), db; select = (:fare_amount, :tip_amount))
```

I'll also be giving a live tutorial on JuliaDB along with OnlineStats integration on Wednesday: https://www.youtube.com/watch?v=d5SzUh2_ono
