### ISSUE TITLE
Stats for timeseries 

### ISSUE THREAD

**Issue by ivborissov** [joshday/OnlineStats.jl#104]
Hi,
I have a solution of Differential Equation which is a number of arrays with values at a given point of time: 
```
julia> sol
2-element Array{Array{Float64,1},1}:
 [1.0e-15, 9.9999e-16, 10.0, 9.9006, 9.80208, 9.70455, 9.60799]
 [1.0e-15, 1.00001e-15, 0.0001, 0.0995027, 0.198015, 0.295548, 0.39211]
```
Doing MonteCarlo simulations I want to calculate OnlineStats like Mean(), Variance(), PQuantile() for each timepoint in each solution component 

I am trying to group statistics by types and update them  like:
```
num_sol = 2
num_t = 7

s =Series(Group(fill(num_t*Mean(),num_sol)))
```
However I don't find a proper way to update (`fit!`) such `Group` of `MVs`. Is such composition supported or there is a more suitable approach to this problem?

**Comment by ivborissov** [comment]
Ah, sorry. I've found the issue in my code. Instead of `fill(num_t*Mean(),num_sol)` I tried smth like `[num_t*Mean() for i in 1:num_sol]`
```
num_sol = 2
num_t = 7

s =Series(Group([num_t*Mean() for i in 1:num_sol]))
```
Now `fit!(s, sol)` works fine. However I still doubt if I've found the optimal solution))

**Comment by joshday** [comment]
There's no built-in way of handling Array of Array.  If I understand what you're trying to do correctly, I'm not sure you're example is doing what you want.  You're trying to calculate stats on the `j`-th element for each of the Vectors? 

You can write out the loop yourself to make things a little more clear:

```julia
s = Series(7Mean())

for sol_i in sol
    fit!(s, sol_i)
end
```

**Comment by ivborissov** [comment]
Yes. I am trying to calculate stats on the `j`-th element for each of the Vectors. Eventually it seems the following code works correct for 2 Vectors of 5 elements:
```
julia> s = Series(Group([5Mean() for i in 1:2]))
▦ Series{1}
│ EqualWeight | nobs=0
└── Group : String["MV", "MV"]
julia> x=rand(5)
5-element Array{Float64,1}:
 0.35868
 0.203063
 0.32398
 0.28474
 0.203017
julia> y=rand(5)
5-element Array{Float64,1}:
 0.40646
 0.366081
 0.614274
 0.40396
 0.693309
julia> fit!(s, [x, y])
▦ Series{1}
│ EqualWeight | nobs=1
└── Group : String["MV", "MV"]
julia> value(s)[1]
2-element Array{Array{Float64,1},1}:
 [0.35868, 0.203063, 0.32398, 0.28474, 0.203017]
 [0.40646, 0.366081, 0.614274, 0.40396, 0.693309]
```
Might be not the best solution but it works. Computing OnlineStats is a great way to reduce MonteCarlo iterations so it could be a great feature for DifferentialEquations.jl

**Comment by joshday** [comment]
That just fit each mean with one observation, though?  The output is the same size as the data.

**Comment by ivborissov** [comment]
Yes, my goal was to find the correct "object" to fit it with new observation data (Vector of Vectors) after each iteration. `Series(Group([num_t*Mean() for i in 1:num_sol]))` seems to be a good choice. Of course I have to create such `Series` for all stats (`Variance(), Quantile()`, etc) but don't know if there is a better solution

**Comment by joshday** [comment]
Ah, your `sol` is one observation, not two!  Got it 👍

**Comment by ivborissov** [comment]
Yes, it is one observation
