### ISSUE TITLE
Performance of CountMap

### ISSUE THREAD

**Issue by MaximilianJHuber** [joshday/OnlineStats.jl#108]
I ran a `CountMap` on an Int64 vector `nr` with 3125181 elements and 253032 unique values:

```
using OnlineStats
s = Series(CountMap(Int64))
@time fit!(s, nr);
```
It took 393.785104 seconds!

Compared to:

```
using StatsBase
@time countmap(nr)
```
running 0.226064 seconds, and

```
@time begin
    u=unique(benr)
    d=Dict([(i,count(x->x==i,nr)) for i in u]);
end
```
running 274.548060 seconds.

I am doing this because, the `reduce` that I run with [JuliaDB](https://github.com/JuliaComputing/JuliaDB.jl) exits with a `StackOverflowError`:

```
@time reduce(CountMap(Int64), table, :NR);
```
which is running on a `Distributed Table with 3125181 rows in 10 chunks`

**Comment by joshday** [comment]
Ah, this should definitely be faster.  I made some changes to CountMap to allow weighting observations which I think I will undo and make a new type for.

**Comment by joshday** [comment]
Fixed on master.  

- `StatsBase.countmap` sorts the data by default (`alg = :radixsort`) which is much faster.
- `alg = :dict` is essentially what `CountMap` does, but StatsBase does some tricks that I don't understand yet.  I'll look into them to see if I can close the timing gap a little more.

```julia
julia> y = rand(1:253032, 3125181);

julia> @time Series(y, CountMap(Int));
  0.416599 seconds (53 allocations: 14.170 MiB)

julia> @time countmap(y, alg = :radixsort);
  0.072687 seconds (58 allocations: 39.944 MiB, 14.20% gc time)

julia> @time countmap(y, alg = :dict);
  0.152801 seconds (48 allocations: 14.170 MiB, 4.83% gc time)
```
