### ISSUE TITLE
Performance Unique(Int64)

### ISSUE THREAD

**Issue by MaximilianJHuber** [joshday/OnlineStats.jl#109]
On a JuliaDB distributed table with 22199683 entries in 5 chunks, I run:

```
@time unique(collect(select(t, :benr)))
```
which runs for about 2 seconds and returns 4627867 entries.

Running:
```
@time collect(reduce(Unique(Int64), t, select=:benr))
```
does not finish in reasonable time.

**Comment by joshday** [comment]
I think I fixed this right around when I fixed `CountMap`.  Try master for now.  I'll get a new release out this weekend.

```julia
julia> y = randn(22199683);

julia> @time Series(y, Unique(Float64));
  5.755609 seconds (166 allocations: 512.342 MiB)
```

**Comment by MaximilianJHuber** [comment]
The `master` [seems](https://github.com/joshday/OnlineStats.jl/issues/112) to be incompatible.

**Comment by joshday** [comment]
I decided to focus on some breaking changes in another branch which are now in master.  I also don't see a way to make `Unique` noticeably faster than `CountMap`, so I plan to drop `Unique` altogether.
