### ISSUE TITLE
switch testing to FactCheck.jl?

### ISSUE THREAD

**Issue by tbreloff** [joshday/OnlineStats.jl#11]
Pros:
- Nicer looking tests/reports
- Can have groupings to easily see sections that are failing
- Testing will continue beyond a failed test (for example, I was changing some tests from `@test` to `@test_approx_eq` one at a time, because any tests after the failed one were not getting run)

Cons:
- Might want to convert existing tests (annoying coding, but we don't have to switch everything if we don't want)

You can see how to use it on the github page, but as examples:
`@test x == y` converts to `@fact x => y`
`@test_approx_eq x y` converts to `@fact x => roughly(y)`

I'll use FactCheck for new stuff that I'm working on, and you can make the judgement call on whether you want to switch to it.

**Comment by joshday** [comment]
I haven't seen FactCheck before.  I'll try it out.  It sounds worth it just from continuing testing beyond a failed test.

**Comment by joshday** [comment]
Besides quantile regression, all tests now use FactCheck.  Quantile regression types still need to be updated to use Weighting.
