### ISSUE TITLE
Add function to merge many series

### ISSUE THREAD

**Issue by tk3369** [joshday/OnlineStats.jl#114]
I have a bunch of Series objects and would like to merge them altogether.  I can write a custom function but thought it could be added to the library instead.

An example:
```julia
x = rand(10,1000)
ss = [Series(x[i,:], Mean(), Variance()) for i in 1:size(x,1)]
```

This looks quite performant:
```julia
function mergeall(ss)
    final = Series(Mean(), Variance())
    for s in ss
        merge!(final, s)
    end
    final
end
```

Compare with a generic reducer like `foldr`:

```julia
julia> mergeall(ss)
▦ Series{0}
│ EqualWeight | nobs=10000
├── Mean(0.497563)
└── Variance(0.0844097)

julia> foldr(merge, ss)
▦ Series{0}
│ EqualWeight | nobs=10000
├── Mean(0.497563)
└── Variance(0.0844097)

julia> @benchmark mergeall($ss)
BenchmarkTools.Trial: 
  memory estimate:  1.28 KiB
  allocs estimate:  52
  --------------
  minimum time:     1.363 μs (0.00% GC)
  median time:      1.565 μs (0.00% GC)
  mean time:        1.862 μs (7.75% GC)
  maximum time:     314.703 μs (96.39% GC)
  --------------
  samples:          10000
  evals/sample:     10

julia> @benchmark foldr($merge, $ss)
BenchmarkTools.Trial: 
  memory estimate:  6.47 KiB
  allocs estimate:  144
  --------------
  minimum time:     60.096 μs (0.00% GC)
  median time:      61.037 μs (0.00% GC)
  mean time:        67.660 μs (0.98% GC)
  maximum time:     2.676 ms (92.84% GC)
  --------------
  samples:          10000
  evals/sample:     1
```

The above `mergeall` function isn't generic enough because the stats are hardcoded.  Maybe it would be good to have a `similar` function that initialize an empty Series with the same stats from the first object in the array.

**Comment by joshday** [comment]
I think this functionality is already built into Julia with the `reduce` function.  Let me know if that's sufficient for you and I'll close the issue.

```julia
reduce(merge!, Series(Mean(), Variance()), ss)
```

**Comment by tk3369** [comment]
The `reduce` function above works perfectly and is performant!  However, I still need to match the _shape_ of the Series and provide the same statistics as the objects in the `ss` array.  It would be nice to have some kind of a `similar` function, or a convenient function that hides this away from a user.

The `foldr` method seems to be carrying a mutable state and provides bad results if I run more than once.... 

```
julia> foo2(ss) = foldr(merge!, ss)
foo2 (generic function with 1 method)

julia> x = rand(10, 1000); ss = [Series(x[i,:], Mean(), Variance()) for i in 1:size(x,1)];

julia> foo2(ss)
▦ Series{0}
│ EqualWeight | nobs=10000
├── Mean(0.497162)
└── Variance(0.0823266)

julia> foo2(ss)
▦ Series{0}
│ EqualWeight | nobs=55000
├── Mean(0.495133)
└── Variance(0.0819764)
```

**Comment by joshday** [comment]
`merge!` is going to mutate the stats, so you can use `merge` with worse performance or provide the `v0` argument.  I'm concerned the amount of effort to match `reduce`'s performance won't be worth it, but I'll leave this open if someone else wants to tackle it.

**Comment by joshday** [comment]
I'm going to close this in favor of the workarounds provided in the issue.
