### ISSUE TITLE
Skewness calculation issue

### ISSUE THREAD

**Issue by tk3369** [joshday/OnlineStats.jl#115]
It appears that the calculation in the `skewness` function is a bit off.  Please take a look at this Discourse post for more details.  

https://discourse.julialang.org/t/skewness-kurtosis/9652/5?u=tk3369

**Comment by joshday** [comment]
Ah, figured it out.  I was using a method-of-moments estimator with the unbiased version of the variance when it should've been biased.  Fixed on master, but note that master has big breaking changes to the design of OnlineStats, namely you don't need to wrap stats in a Series anymore.

```julia
julia> y = randn(1000);

julia> skewness(y)
-0.12712470723880606

julia> skewness(fit!(Moments(), y))
-0.12712470723880614
```
