### ISSUE TITLE
whichchild BoundsError while training FastTree/Forest (with potential fix)

### ISSUE THREAD

**Issue by harveydevereux** [joshday/OnlineStats.jl#116]
### Error

I've been using *FastTree* and *FastForest* and noticed that certain random data generations cause
*whichchild* to access an array at element 0 throwing a BoundsError during the call
to *fit!* for example

```julia
srand(218)
X,Y = OnlineStats.fakedata(FastNode, 10^4, 1)
fit!(FastTree(1, splitsize=100),(X,Y))
```

Interestingly the same with FastForest runs just fine. An example of the error with
FastForest is

```julia
srand(37)
X,Y = OnlineStats.fakedata(FastNode, 10^4, 1)
fit!(FastForest(1, splitsize=44),(X,Y))
```

In each case the error output is: 

BoundsError: attempt to access 1-element Array{Float64,1} at index [0]

### Fix 

I believe the error comes from the default value *ind=0* at line 55 of *fastree.jl* in the *split!* function 
since at line 92 the assignment *o.j = ind* is made apparently the 0 carries through sometimes and
causes the error at line 44 when *x[o.j]* is called in *whichleaf*.

Changing *ind=0* to *ind=1*  on line 55 of *fasttree.jl* fixed all the problems for me, i.e I can train with any splitsize using this change and never get any bounds errors.

**Comment by joshday** [comment]
Thanks for reporting this.  A bug report + fix is always great.  

I made a mistake in calculating the information gain.  It was occasionally `NaN`, which screwed up the loop that would set `o.j = ind`.  Fixed on master!

**Comment by joshday** [comment]
Nevermind, just got a test failure...investigating now.

**Comment by joshday** [comment]
Okay, now everything's fixed!
