### ISSUE TITLE
__precompile__ not supported anymore?

### ISSUE THREAD

**Issue by tkf** [joshday/OnlineStats.jl#117]
It looks like that `__precompile__` was removed in caaac407c391b4d06752b40d474c81a70fdd26a6 (which was mentioning https://github.com/joshday/OnlineStats.jl/pull/111).  Was it a conscious decision?  From the log, it was not super clear.  It would be great if you can put it back.

**Comment by joshday** [comment]
Thanks for catching that!  Not intentional at all.  It's back on master.

**Comment by tkf** [comment]
Thank you!
