### ISSUE TITLE
GLMs in OnlineStats StatsLearn

### ISSUE THREAD

**Issue by dataPulverizer** [joshday/OnlineStats.jl#118]
Do you currently have a way to specify GLM log-likelihoods in your `StatsLearn` function or does the user have to build it themselves?

Can you use StatsLearn to fit GAM models? Has it been tried successfully?

**Comment by joshday** [comment]
You can use a linear predictor with any of the loss functions in https://github.com/JuliaML/LossFunctions.jl

For example, fitting a logistic regression model would look like 

```julia
o = StatLearn(n_predictors, LogitMarginLoss()

fit!(o, (x, y))
```

**Comment by joshday** [comment]
> Can you use StatsLearn to fit GAM models?

I'm only a little familiar with GAMs, but it looks like some of the math would work out with `StatLearn` pretty well.

**Comment by dataPulverizer** [comment]
Thank you very much for the information. I guess I'll close this issue.
