### ISSUE TITLE
Weighting for stochastic methods

### ISSUE THREAD

**Issue by joshday** [joshday/OnlineStats.jl#12]
Stochastic types use weights of the form `nbatches ^ -const` where `const > .5 && const <= 1`, which doesn't fit into the current weighting scheme.  I need to think a bit more about how to handle this.

**Comment by tbreloff** [comment]
Could be a straightforward type if you assume the weight method is called once per batch?  Note I don't know the correct "f" function... 
```
type StochasticWeighting <: Weighting
  nbatches::Int
  someconst::Float64
  StochasticWeighting(someconst::Float64) = new(0, someconst)
end

weight(w::StochasticWeighting, n1, n2) = f(w.nbatches ^ (-w.someconst))
```

**Comment by joshday** [comment]
That'll do it.  Here `f(x) = x`.  Another thought I had was 
```
weight(w::StochasticWeighting, n1, n2) = n2 ^ (-w.someconst)
```

I think it could then be a subtype of `Weighting`.  `update!()` methods would use
```
weight(o)
```

 `updatebatch!()` methods use
```
weight(o, nbatches)
```

**Comment by joshday** [comment]
Actually, it could only be a `Weighting` subtype for
```julia
function weight(w::StochasticWeighting, n1, n2) 
    w.nb += 1
    n2 ^ (-w.someconst)
end
```
That's bad form without `!` in the function name.  I won't add it as a subtype.

**Comment by joshday** [comment]
I currently do have StochasticWeighting as a subtype of Weighting.  Instead of weighting a new observation as `1/n`, it will get weighted somewhere between `1/sqrt(n)` and `1/n` depending on the parameter `r`.

How "bad" is it to have `weight()` alter the argument without `!` in the function name?

```julia
type StochasticWeighting <: Weighting
    r::Float64
    nb::Int64   # number of batches
    λ::Float64  # minimum step size
    function StochasticWeighting(r::Float64 = .51, λ::Float64 = 0.)
        @assert r > .5 && r <= 1
        @assert λ >= 0. && λ <= 1.
        new(r, 0, λ)
    end
end
@compat function weight(w::StochasticWeighting, unused, n2)
    w.nb += n2
    max(Float64(w.nb) ^ -w.r, w.λ)
end
```
Thus calling `weight(o)` will increment `w.nb` by one before returning the weight.

**Comment by tbreloff** [comment]
I think it's totally fine to have `weight(o)` instead of `weight!(o)` in this case.  The value of keeping the interface consistent is more than the value of hinting that something will be updated.

**Comment by joshday** [comment]
Sounds good to me.
