### ISSUE TITLE
Merging two empty series results in a mean value of NaN.

### ISSUE THREAD

**Issue by kafisatz** [joshday/OnlineStats.jl#125]
See example
Is this intentional?
For a use case of mine I would prefer if the value were 0.0 insted of NaN
```
julia> total=Series(OnlineStats.Mean(),OnlineStats.Variance())
Series
  ├── Mean: n=0 | value=0.0
  └── Variance: n=0 | value=1.0

julia> total2=Series(OnlineStats.Mean(),OnlineStats.Variance())
Series
  ├── Mean: n=0 | value=0.0
  └── Variance: n=0 | value=1.0

julia> merge!(total,total2)
Series
  ├── Mean: n=0 | value=NaN
  └── Variance: n=0 | value=1.0

```

**Comment by joshday** [comment]
Hmm, `merge!`-ing empty stats isn't something I considered.  It's only well-defined if at least one of the stats has seen observations.

I agree that this should work as expected, but will require changing the OnlineStat interface from `Base.merge!` to `_merge!` so that I can define something like 


```julia
function Base.merge!(o::OnlineStat, o2::OnlineStat)
    nobs(o) == 0 && nobs(o2) == 0 && return o
    _merge!(o, o2)
end
```

**Comment by joshday** [comment]
Fixed on master.

```julia
julia> merge!(Mean(), Mean())
Mean: n=0 | value=0.0
```
