### ISSUE TITLE
Fitting KMeans chokes on NamedTuples with table input

### ISSUE THREAD

**Issue by ElOceanografo** [joshday/OnlineStats.jl#126]
Trying to fit a K-means model to a JuliaDB `table` doesn't work. MWE:

```julia
using JuliaDB
using OnlineStats

varnames = [:a, :b, :c, :d, :e]
p = length(varnames)
n = 1000
tab = table([randn(n) for i in 1:p]..., names=varnames)
fit!(CovMatrix(), tab) # works
fit!(KMeans(p, 3), randn(n, p)) # works
fit!(KMeans(p, 3), tab) # fails
```
The error message is:
```julia
ERROR: MethodError: Cannot `convert` an object of type IndexedTables.NextTable{IndexedTables.Columns
{NamedTuples._NT_a_b_c_d_e{Float64,Float64,Float64,Float64,Float64},NamedTuples._NT_a_b_c_d_e{Array{
Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1}}}} to an object of ty
pe Array
This may have arisen from a call to the constructor Array(...),
since type constructors fall back to convert methods.
```
The problem seems to be that the `_fit!` [method ](https://github.com/joshday/OnlineStats.jl/blob/886c542adb23613d67f96b0a1ff9707bc13a961a/src/stats/stats.jl#L672) for `KMeans` assumes that each new datapoint is a `Vector`, and when its a `NamedTuple` the assignments and indexing break.

Writing out [these ](https://github.com/joshday/OnlineStats.jl/blob/886c542adb23613d67f96b0a1ff9707bc13a961a/src/stats/stats.jl#L676) [lines](https://github.com/joshday/OnlineStats.jl/blob/886c542adb23613d67f96b0a1ff9707bc13a961a/src/stats/stats.jl#L679) as explicit loops for `i=1:p` seems like an easy fix...if there are no obvious issues with that approach I can make a PR.

**Comment by joshday** [comment]
Thanks for the issue and the fix!  Fixed on master.
