### ISSUE TITLE
Rolling example 

### ISSUE THREAD

**Issue by flare9x** [joshday/OnlineStats.jl#127]
Here I want the maximum and minimum on a rolling window: 

x = collect(1:1:100)
out = zeros(x)
out = Float64.(out)
len=5
for i = len:length(x)
out[i] = fit!(Extrema(), x[i-len+1:i])
end

That is how I would do it - although in this Extrema function. I do not need the results merged. At every [i] step I would actually save the max, min for the specified rolling window  x[i-len+1:i] 

I think having more flexibility like this would be good.

**Comment by joshday** [comment]
This is a dup of #20 so I'll close this issue.  I'd like to figure out a method of doing this generally with a wrapper type, something like `Window(Extrema(), 5)`.
