### ISSUE TITLE
CovMatrix hard-parameterized for Float64

### ISSUE THREAD

**Issue by ElOceanografo** [joshday/OnlineStats.jl#132]
I was just trying to do a Hilbert EOF decomposition of a large dataset (basically the same thing as a regular PCA except that the real input data have been Hilbert-transformed, so they have complex values).  Fitting a `CovMatrix` to complex data does not work, since its `value`, `a`, and `b` fields are [defined explicitly](https://github.com/joshday/OnlineStats.jl/blob/e8aac42e74b0b7c11da1af8bd52efcee30485f16/src/stats/stats.jl#L277) for `Float64`: `fit!`ing it fails, in the call to `smooth!`, with an `InexactError()` when it can't convert the `Complex` data to `Float64`.

Is there any reason not to loosen those type parameters to `Number`?

**Comment by joshday** [comment]
I think `CovMatrix` could certainly be parameterized to cover more number types.  I'd accept a PR if you're willing to give it a shot.  I'd guess I won't have time to look at it myself until late next week.

**Comment by ElOceanografo** [comment]
Sounds good. Giving it a shot now, unless you've already started.

**Comment by joshday** [comment]
Fixed by @ElOceanografo 👍
