### ISSUE TITLE
Support frames

### ISSUE THREAD

**Issue by yakir12** [joshday/OnlineStats.jl#134]
I often need to do some stats on image frames from some video. Sometimes the size of the images, their number, and their encoding means it's too big to hold in memory. So... Can we have the stats hold whole frames (i.e. arrays of colors, or just arrays of floats)?
So I could:
```julia
y = [rand(10,10) for i in 1:3]
s = Series(Mean())
fit!(s, y)
```
and have it return the mean across the outer dimension (so it's size would be 10 x 10)?

**Comment by joshday** [comment]
> Both use however twice the memory that this approach does

I'd guess swapping out the broadcasting with an explicit loop would help.  You're also keeping track of less state/calculating fewer things in your function than `Mean` needs to.  

Making `FTSeries` better is on my list of things to do.  It currently doesn't tap into Julia inference to figure out the what the return type of the transform is.  Maybe https://github.com/JuliaArrays/MappedArrays.jl would be a better approach for you.

**Comment by yakir12** [comment]
This is great, thank you so much for the help.

**Comment by JobJob** [comment]
Thanks to both of you for raising and providing solutions to this issue.

FWIW I benchmarked the 2 approaches and found they were pretty much the same in terms of memory and performance. 
```
ElementwiseStat BenchmarkTools.Trial:
  memory estimate:  156.33 KiB
  allocs estimate:  2
  --------------
  minimum time:     94.104 μs (0.00% GC)
  median time:      185.957 μs (0.00% GC)
  mean time:        221.334 μs (10.07% GC)
  maximum time:     49.221 ms (99.57% GC)
  --------------
  samples:          10000
  evals/sample:     1
========================================================
Broadcasted stat BenchmarkTools.Trial:
  memory estimate:  156.33 KiB
  allocs estimate:  2
  --------------
  minimum time:     97.328 μs (0.00% GC)
  median time:      189.127 μs (0.00% GC)
  mean time:        223.295 μs (9.99% GC)
  maximum time:     49.724 ms (99.60% GC)
  --------------
  samples:          10000
  evals/sample:     1
```

```
using BenchmarkTools
using OnlineStats
import OnlineStatsBase

mutable struct ElementwiseStat{T<:OnlineStat} <: OnlineStat{Matrix}
    value::Matrix{T}
    n::Int
end

ElementwiseStat(rows, cols, stat = Mean()) = ElementwiseStat([copy(stat) for i in 1:rows, j in 1:cols], 0)
function OnlineStatsBase._fit!(o::ElementwiseStat, y)
    fit!.(o.value, y)
    o.n += 1
end

const nrows = 100
const ncols = 200
const data_count = 10
const data = [rand(Float64, nrows, ncols) for i in 1:data_count]

const elw_stat = ElementwiseStat(nrows, ncols, Variance())
# fit!(elw_stat, data)
b_elw = @benchmark fit!($elw_stat, $(data[2]))

const stat_mat = [Variance() for i in 1:nrows, j in 1:ncols]
# foreach(img->fit!.(stat_mat, img), data)
b_bcast = @benchmark fit!.($stat_mat, $(data[2]))

println()
display.((Text("ElementwiseStat "), b_elw))
println(); println("========================================================")
display.((Text("Broadcasted stat "), b_bcast))
println()
```

**Comment by yakir12** [comment]
Wow, that is damn near identical. Awesome.
