### ISSUE TITLE
Nondeterministic test failures for Complex CovMatrix

### ISSUE THREAD

**Issue by joshday** [joshday/OnlineStats.jl#138]

**Comment by joshday** [comment]
I occasionally get NaNs in the tests for CovMatrix with Complex values.  @ElOceanografo I'm pinging you in case you have ideas.

**Comment by ElOceanografo** [comment]
Nondeterministic failures...the best kind of failures.  I wonder if it's because `≈` works slightly differently for complex numbers (i.e., because it has to test equality in two dimensions)?

**Comment by gdkrmr** [comment]
I get these failures in ~50% of test runs.

**Comment by joshday** [comment]
What machine are you using?  I can almost never reproduce this on my mac, even though the tests fail on Travis about 50% as well.

**Comment by gdkrmr** [comment]
Ubuntu 16.04, an i7 5xxxU and a self-compiled julia.

**Comment by joshday** [comment]
I think I should have closed this a while ago.  I started creating the initial values with `zeros(T, p)` instead of `Vector{T}(undef, p)` and that seems to have fixed it 🤷‍♂️
