### ISSUE TITLE
Add T score or "Mean/Std" in Univariate Statistics

### ISSUE THREAD

**Issue by evveric** [joshday/OnlineStats.jl#143]
Hello, I would like to know how to generate T score , or Mean() / Sqrt( Variance() ), for Univariate Statistics?

https://joshday.github.io/OnlineStats.jl/latest/stats_and_models/

From above, only mean, variance, quantile, max/min etc. 

I would like to have a Measurement of "Statistical Significance" for a Product of two variables.

e.g., I have x = Temperature change today,  y = Humidity change yesterday
both are Timeseries and zero-mean

I have a new variable z
z = x.*y

z will measure the significance or correlation between x and y. so I want to check the Mean(z) / Stdev(z)

Is it possible with current algo already?

Thank you

**Comment by joshday** [comment]
Not sure I completely follow what you're trying to do, but it would be straightforward to roll your own ratio of (mean / stdv) using https://github.com/joshday/OnlineStatsBase.jl.


```julia
using OnlineStatsBase, Statistics

struct Thing <: OnlineStat{Number}
    m::Mean{Float64}
    v::Variance{Float64}
    Thing() = new(Mean(), Variance())
end
OnlineStatsBase.nobs(o::Thing) = nobs(o.m)
OnlineStatsBase._fit!(o::Thing, y) = (fit!(o.m, y); fit!(o.v, y))
OnlineStatsBase.value(o::Thing) = value(o.m) / std(o.v)

# done!
fit!(Thing(), randn(10^6))
```

**Comment by evveric** [comment]
Thank you! it works perfectly
