### ISSUE TITLE
BoundsError when training FastForest

### ISSUE THREAD

**Issue by iqml** [joshday/OnlineStats.jl#150]
Hi, thanks for creating this package, it's really interesting.

I have encountered an error that may be related to the closed issue #116  but is still occurring in version v0.26.1

When training with certain data, a `BoundsError` occurs. This happens non-deterministically with a large data set I am working with, but here is a small example that seems to cause the error every time.

```julia
using OnlineStats

x = [2, 2, 1, 2, 1, 2, 2, 2, 2, 2]
y = [1, 1, 1, 2, 1, 1, 1, 1, 1, 1]
model = FastForest(1; nt = 1, splitsize = 2)
fit!(model, zip(eachrow(x), y))
```

This results in the message:

```
ERROR: BoundsError: attempt to access 1-element Array{Int64,1} at index [0]
```

Thanks

**Comment by joshday** [comment]
I *think* this was a case of an attempted split when all the observations were identical (`splitsize=2` and first two obs are the same).  I pushed a quick fix to master, but I'll leave this open as I should look into this further.

**Comment by iqml** [comment]
Yes that has fixed the problem, thank you.
