### ISSUE TITLE
ExpandHist does not update counts on expand!

### ISSUE THREAD

**Issue by kolia** [joshday/OnlineStats.jl#154]
Hi @joshday 

Looking at ExpandingHist's [expand!](https://github.com/joshday/OnlineStats.jl/blob/65c2ca8574cf430f013a4783b72990c1b796c88f/src/stats/histograms.jl#L177-L186) it looks like the `edges` range gets expanded but the `counts` don't get updated.  Is this intentional, or am I missing something?  Seems like a bug to me, unless you assume that future data will overwhelm the data seen so-far, which is not a great assumption.

**Comment by joshday** [comment]
Oh yikes, that’s why I never exported it...I never finished the implementation.  I’ll see if I can wrap that up this week.

**Comment by joshday** [comment]
fixed and exported (on master)
