### ISSUE TITLE
Regression results not right

### ISSUE THREAD

**Issue by xiaodaigh** [joshday/OnlineStats.jl#155]
Tried my best to follow your example in #89 and I tried to fit a linear regression with no L1 nor L2 penalty. But the result don't match up with a normal fit

```julia
using RDatasets

cars = dataset("datasets", "cars")

# example
m = lm(@formula(Dist~-1+Speed), cars)
coef(m) # 2.9


using OnlineStats, LossFunctions, PenaltyFunctions 
# fit using OnlineStats.jl
y = cars[:Dist]
x = cars[:Speed]

o = StatLearn(1, L2DistLoss(), NoPenalty())

fit!(o, zip(eachrow(x), y))

coef(o) # ~0.0
```

**Comment by alesasse** [comment]
I tried to run your code, but I had a different outcome. I have
```
coef(o)  # ~ -1.87e91
```
I suppose the problem is due to the algorithm used for learning, defaulted to SGD, probably not converging.
Try instead
```
o = StatLearn(1, L2DistLoss(), NoPenalty(), ADAM())
o2 = LinReg()
fit!(o, zip(eachrow(x), y))
fit!(o2, zip(eachrow(x), y))
coef(o) # ~ 2.93
coef(o2) # ~ 2.91
```

**Comment by xiaodaigh** [comment]
Ok, I see. ADAM() is a lot better!

**Comment by xiaodaigh** [comment]
Sounds like you need to activate a separate environment. But I will check out MSPI.
