### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by tbreloff** [joshday/OnlineStats.jl#16]
Did log.jl break on 0.3.7?  Maybe we can debug together?  It's nice to use... you can do:
```
x = "world"
LOG("Hello", x)  # prints "INFO: Hello world [filename:linenumber]"
log_severity(ERROR)
LOG("Hello", x)  # doesn't print... severity not high enough
LOG(ERROR, "Hi") # prints "ERROR: Hi [filename:linenumber]"

log_severity(INFO)
y = 5
@LOG x y   # prints "INFO: x: world y: 5 [filename:linenumber]"
```

I'll probably add `@DEBUG` and `@ERROR` macros too.

This is cool so you can add verbose logging to your stuff and turn it on/off for different runs (using `log_severity()`) without reloading.

**Comment by joshday** [comment]
I haven't used your `log.jl` stuff yet.  That does look really nice.  I'll try it out.

**Comment by joshday** [comment]
That's right, I remember getting this: `ERROR: @enum not defined`

**Comment by tbreloff** [comment]
Ah... enums  :(  I'll need to think on that.

**Comment by tbreloff** [comment]
I may try to split this off into a separate package, or trash it and look for other options.

**Comment by tbreloff** [comment]
I added enums to this package, but I'm not sure if it will work for you.  Can you test if you can LOG("HI")?

**Comment by joshday** [comment]
Now it's `ERROR: @noinline not defined`

**Comment by tbreloff** [comment]
Ok guess this won't work until you upgrade.  I'll try to get rid of enums.

**Comment by joshday** [comment]
Have you run into any "bad builds" from using the prerelease versions?  I wouldn't mind upgrading...I just don't know what I'd be getting myself into.

**Comment by tbreloff** [comment]
Yes... especially the recent "Tupocalypse", where they changed the syntax and internals of tuples.  Everything everywhere broke.  However if you find a commit that works, you can just keep that commit for a while.  For example, I'm on commit 58cef56 and it seems to be mostly stable.  At some point I'll take the plunge and update again, but then I'll have a lot of fixing before my code works again.

**Comment by tbreloff** [comment]
Please see my latest commit... I removed enums from log.jl

**Comment by joshday** [comment]
No error from log anymore.  

There looks like an issue with some letters as subscripts.  I get an error anywhere you have `\beta\_n` in ofls.jl.

Using tab completion (`\beta (tab) \_n (tab)` in the terminal makes this:

![screen shot 2015-05-04 at 12 17 00 pm](https://cloud.githubusercontent.com/assets/8075494/7457037/7ee61d5c-f257-11e4-83a8-52ebf76a5c01.png)

**Comment by tbreloff** [comment]
Oh boy... fun!  Guess I'll change the subscript
