### ISSUE TITLE
KMeans implementation problem

### ISSUE THREAD

**Issue by grahamas** [joshday/OnlineStats.jl#163]
Currently, the KMeans `fit!` function is defined with
```
fill!(o.buffer, 0.0)
for k in eachindex(o.buffer)
    cluster = o.value[k]
    for j in eachindex(x)
        o.buffer[k] = norm(x[j] - cluster.value[j])
    end
end
k_star = argmin(o.buffer)
cluster = o.value[k_star]
smooth!(cluster.value, x, o.rate(cluster.n += 1))
```
The `j` loop seems to repeatedly overwrite the same value. As far as I can tell, the correct implementation would be 
```
fill!(o.buffer, 0.0)
for k in eachindex(o.buffer)
    cluster = o.value[k]
    o.buffer[k] = norm(x .- cluster.value)
end
k_star = argmin(o.buffer)
cluster = o.value[k_star]
smooth!(cluster.value, x, o.rate(cluster.n += 1))
```
Which just stores the norm difference between the target vector x and each cluster center in the buffer, and then finds the minimizing cluster.

I'm making a PR right now, but let me know if I'm missing something.

**Comment by joshday** [comment]
Good catch!  

If I'm remembering correctly, a while back I was trying to remove some temporary allocations.  I successfully reduced the allocations, but apparently at the cost of making the clustering based on the last element only  🙃

**Comment by joshday** [comment]
Sorry to steal the PR from under you, but it's fixed on master now
