### ISSUE TITLE
References for algorithms 

### ISSUE THREAD

**Issue by baggepinnen** [joshday/OnlineStats.jl#166]
Thanks for an awesome package! 

I was trying to find a reference and read up on the `MSPI` algorithm, but googling it led me to an ocean of similarly named algorithms. It would be great if docstring for the different algorithms and weight choices contained some reference so that one can learn about their properties and make an informed choice.

**Comment by joshday** [comment]
Thanks!  MSPI details currently only exist in my dissertation.  Publication is in the works.  

https://repository.lib.ncsu.edu/handle/1840.20/34945

I’ll add some ref links to the docs as I have time.

**Comment by joshday** [comment]
References have been added on master
