### ISSUE TITLE
Implement IPLS

### ISSUE THREAD

**Issue by tbreloff** [joshday/OnlineStats.jl#17]
Partial Least Squares (PLS) is a technique which effectively combines PCA and regression in the same algo.  The goal is to find reduced dimension linear combinations of X (i.e. T = XW) that have high covariance with Y (i.e. regressing Y = beta \* T + error)

Reviewing Zeng et al (2014): "Incremental partial least squares analysis of big streaming data" as a possible algo reference.

**Comment by joshday** [comment]
@tbreloff What is the state of OnlinePLS?  Also OnlinePCA and OnlineFLS?  I don't have these in the documentation, just because I haven't really used them.  I'd love to include them to the feature list.

**Comment by tbreloff** [comment]
I think they are all functional, or close to functional, but they need tests. The PLS would be great to have... I do feel like FLS is partially redundant.   Do you have time to write tests for them? I probably wont get to it in the near future.

**Comment by joshday** [comment]
Not this week, but I'll take a look when I get a chance.

**Comment by joshday** [comment]
There's too many possible things to implement to have issues for them all.  

I'm going to close these types of issues and leave the blanket statement "Pull Requests Welcome" so that issues stay actionable.
