### ISSUE TITLE
Extract stats from series

### ISSUE THREAD

**Issue by yakir12** [joshday/OnlineStats.jl#175]
I must have missed something. How can I extract the stats from a collection of series:
```julia
using OnlineStats, StaticArrays
o = [Series(Mean(), Variance()) for i in 1:2]
for v in repeat(randn(SVector{2, Float64}, 1000), 1000)
    fit!.(o, v)
end
μσ = value.(o) #<- this is one way, although it is not clear what is what
```
But I had thought that simply doing a `mean.(o)` would suffice. Or perhaps if `value` would have returned a named tuple so I'd know which element is which statistics.

**Comment by yakir12** [comment]
I discovered I can/should do this:
```julia
o = [Variance() for _ in 1:2]
for v in repeat(randn(SVector{2, Float64}, 1000), 1000)
    fit!.(o, v)
end
μ = mean.(o)
σ = std.(o)
```

**Comment by joshday** [comment]
With `o = [Series(Mean(), Variance()) for i in 1:2]`, you can access `o[1].stats` and `o[2].stats`.

This is somewhat related: https://discourse.julialang.org/t/retrieve-onlinestat-series-statistics/31901
