### ISSUE TITLE
Stress that fit! is an update in the docs

### ISSUE THREAD

**Issue by CarloLucibello** [joshday/OnlineStats.jl#176]
First time I bumped into this package I thought the `fit!` function needed the whole dataset as an iterable object, something which was not practical for my application. Having a second glance at the package instead, I understood that datapoints can be fed one by one or in chunks and `fit!` will keep updating the statics as it should. 

Probably I've been very stupid and most people won't be misled like that, but I think it would be nice to add somewhere to the documentation one example with multiple calls to fit!, as in
```julia
fit!(m, 1.2)
fit!(m, 0.7)
....
```
since all the examples I have seen use a single call to fit! with an iterable argument.

**Comment by joshday** [comment]
Added an example to the README and the first page of the docs.

**Comment by CarloLucibello** [comment]
nice, thanks
