### ISSUE TITLE
User-specified weighting

### ISSUE THREAD

**Issue by joshday** [joshday/OnlineStats.jl#18]
It would be a nice feature to allow users to specify their own weights along with data.  This would likely only be a method available for `MyStatistic{EqualWeighting}` types.

`update!(o, y, w)` where `w` is a weight vector.

edit: adding a checklist by directory:
- [ ] distributions
- [ ] glm
- [ ] linearmodel
- [ ] multivariate
- [ ] quantileregression
- [ ] streamstats
- [ ] summary

**Comment by tbreloff** [comment]
We have a couple options here, but the easiest might be just to add a lambda param to each update:
```
function update!(o::Variance, y::Float64, λ = weight(o))
  ...
end
```

**Comment by joshday** [comment]
Easy to implement and user-friendly.  I'm on board with that.

**Comment by tbreloff** [comment]
Note: For performance it should probably be:
```
function update!(o::Variance, y::Float64, λ::Float64 = weight(o))
  ...
end
```

and we'll have to be careful that adding an extra float param doesn't get multi dispatch confused. (we could always make it a keyword argument if we run into trouble)

**Comment by slundberg** [comment]
Did anything ever come from this? I would love to switch over to use OnlineStats for my current online mean and bootstrap computations, but I need to individually weight samples.

**Comment by joshday** [comment]
Not yet, but you can hack the system:

```julia
o = Mean()
for i in 1:length(y)
    o.weight = ExponentialWeight(weightvec[i])
    fit!(o, y[i])
end
```

**Comment by joshday** [comment]
I'll need to think some more on how to add this feature since `fit!` already takes an optional parameter for updating in batches.

**Comment by slundberg** [comment]
Thanks. Though just to clarify `weightvec[i]` above would need to be adjusted to account for how many samples were observed in the past, not just the raw weight of that sample:

```julia
o = Mean(ExponentialWeight(0.0))
for i in 1:length(y)
    sumw = o.weight.λ + weightvec[i]
    o.weight.λ = weightvec[i]/sumw
    fit!(o, y[i])
    o.weight.λ = sumw
end
```

**Comment by slundberg** [comment]
Since there is already a `fitbatch!` method I am not sure why `fit!` also need a batch parameter. But perhaps I am missing something.

**Comment by joshday** [comment]
`fitbatch!` isn't exported.  I'd like `fit!` to support both singleton and batch updates.

**Comment by slundberg** [comment]
Ah. Makes sense. For now I am doing:

```julia
immutable ObsWeight
    value::Float64
end          
SpecifiedWeight() = ExponentialWeight(0.0,0)
function fit!(o::OnlineStat{OnlineStats.ScalarInput}, y, w::ObsWeight)
    sumw = o.weight.λ + w.value
    o.weight.λ = w.value/sumw
    fit!(o, y)
    o.weight.λ = sumw
    o
end
```
which can be used as
```julia
a = Mean(SpecifiedWeight())
fit!(a, 1, ObsWeight(2.3))
```

**Comment by joshday** [comment]
I just added a `UserWeight` type on the dev branch.  I need to figure out what the correct syntax should be/whether it makes sense to allow weights and batch size args, etc., but it's a start.

```julia
n = 100
y = randn(n)
w = rand(n)

o = Mean(UserWeight())
fit!(o, w, y)

@show value(o)
@show mean(y, WeightVec(w))
```

```
value(o) = -0.1546876287716332
mean(y,WeightVec(w)) = -0.15468762877163345
```

**Comment by slundberg** [comment]
Great!

My specific use-case is adding one value at a time, then bundling that in a bootstrap stream. Before I saw you updates I got it working for now by editing master. I'll add a PR just so you can see what I did, in case you find any of it useful.

**Comment by joshday** [comment]
Thanks!  I'll take a look.

**Comment by joshday** [comment]
I came up with a better solution.  See `WeightedOnlineStat` at the bottom of the file here: https://github.com/joshday/OnlineStats.jl/blob/dev/src/weight.jl

```julia
using OnlineStats, StatsBase
n = 1000
y = randn(n)
wts = rand(n)

o = WeightedOnlineStat(Mean)
fit!(o, y, wts)
value(o)

y2 = randn(n, 5)
o = WeightedOnlineStat(CovMatrix, 5)
fit!(o, y2, wts)
value(o)
```

**Comment by slundberg** [comment]
Looks good! It seems like there might need to be some super class of `OnlineStat` and `WeightedOnlineStat` so that type definitions like:

```julia
type ScalarPoissonBootstrap{S <: OnlineStat{ScalarInput}} <: Bootstrap{ScalarInput}
```

can apply to both types without duplicating things.

**Comment by slundberg** [comment]
So I have been trying to make the bootstrap code work with the `WeightedOnlineStat` type, but it is not going very well.

Lot's of things assume that you have a `OnlineStat` object, and just because you can weigh the samples individually does not conceptually mean you don't have an `OnlineStat`. But making `WeightedOnlineStat` a subtype of `OnlineStat` would break method dispatch assumptions.

What if you templated OnlineStat on both the input and the Weight object?

```julia
abstract OnlineStat{I <: Input, W <: Weight}
```

Then you can dispatch on specific types of weights:

```julia
fit!(o::OnlineStat{ScalarInput, UserWeight}, y::Real, w::Real)
```

You could then also avoid having a  `WeightedOnlineStat` type even though `OnlineStat` is also weighted (just by using a Weight object).

**Comment by joshday** [comment]
That seems like a good solution.  I'll be able to try that out this weekend.  Let me know if you've already started working on it so we don't duplicate each others' work.

**Comment by slundberg** [comment]
Cool. I have not touched the weighting, and am only working with the
bootstrap to avoid any conflicts. Nice work on this package!

**Comment by joshday** [comment]
Sounds great.  Thanks for your input!

**Comment by joshday** [comment]
I decided not to add the extra parameter for OnlineStat types.  I was worried that the use case we've discussed here isn't general enough.  I changed how `Weight`s and `fit!` work together and touched just about every file in the repo.  The benefit is that there are now `fit!` methods that allow you to overwrite the weight for any given update.  A weighted mean can now be calculated by:

```julia
using StatsBase, OnlineStats
n = 100_000
y = randn(n)
wts = rand(n)

o = Mean()
fit!(o, y, wts ./ cumsum(wts))

value(o) - mean(y, WeightVec(wts))
```

This puts the burden on the user to keep track of the sum of the weights for the denominator, but is general enough for more complex uses like providing your own learning rate for StatLearn.

For anyone interested in the internals I changed, here's a short summary:

```julia
# OnlineStats all have Weight objects that keep track of nobs
# Updating nobs and getting the new weight are now separate actions
function fit!(o::OnlineStat{ScalarInput}, y::Real)
    updatecounter!(o)  # o.weight.nobs += 1
    γ = weight(o)      # get the weight
    _fit!(o, y, γ)     # update the value
    o
end

# Override the weight without losing track of nobs
function fit!(o::OnlineStat{ScalarInput}, y::Real, γ::Float64)
    updatecounter!(o)
    _fit!(o, y, γ)
    o
end

# An OnlineStat needs a _fit! method which takes a weight γ
_fit!(o::Mean, y::Real, γ::Float64) = (o.value = smooth(o.value, y, γ))
```

**Comment by slundberg** [comment]
Nice. Thanks.
