### ISSUE TITLE
How to remove stats from loop?

### ISSUE THREAD

**Issue by programistawpf** [joshday/OnlineStats.jl#181]
This package is very use full !!!  Nice
but s is empty in new Julia outside the loop 
```
julia> s=Series(Mean(), Variance())
Series
  ├── Mean: n=0 | value=0.0
  └── Variance: n=0 | value=1.0

julia> @distributed merge for i in 1:3
       global s
       s=fit!(Series(Mean(), Variance()), randn(10_000))
       end
Series
  ├── Mean: n=30000 | value=0.00343878
  └── Variance: n=30000 | value=0.992379

julia> s
Series
  ├── Mean: n=0 | value=0.0
  └── Variance: n=0 | value=1.0
```
Thanks, Paul

**Comment by joshday** [comment]
Thanks!

If you're basing this off of my example (https://joshday.github.io/OnlineStats.jl/latest/parallel/), I should probably change it to

```Julia
s = @distributed merge for i in 1:3
    fit!(Series(Mean(), Variance(), KHist(20)), randn(10_000))
end
```

I'll admit I'm a little hazy on the magic that happens inside of a `@distributed` block, so the official Julia docs may be of more use to you than I can be.
