### ISSUE TITLE
Bug in KHist cdf

### ISSUE THREAD

**Issue by robertfeldt** [joshday/OnlineStats.jl#182]
This is not what I expected:

```julia
julia> o = OnlineStats.KHist(2)
KHist: n=0 | value=(x = Union{Float64, Int64}[], y = Union{Float64, Int64}[])

julia> fit!(o, [1.0, 1.0, 2.0])
KHist: n=3 | value=(x = [1.0, 2.0], y = [2, 1])

julia> OnlineStats.cdf(o, 1.0)
1.3333333333333333

julia> OnlineStats.cdf(o, 2.0)
1.0
```

This violates two invariants I would expect i.e. cdf never returns a value outside of 0.0 to 1.0 (probability) range, and the cdf for a larger value can never be lower than for a smaller value. Have I misunderstood KHist in some way or is this just a bug? My bet is on the latter. ;)

**Comment by joshday** [comment]
Thanks for reporting!  There was some incorrect logic when the value equals the first bin location.  Fixed on master.

**Comment by robertfeldt** [comment]
Thanks, @joshday, for the quick fix. I'm not sure the smoothing for intermediate bins is correct though since they don't "connect" to the probability values right before and after. See here for example of problems/unexpected behavior:

``julia
o = OnlineStats.KHist(3)
fit!(o, [1.0, 2.0, 2.0, 3.0])

julia> OnlineStats.cdf(o, 1.0) # expect 0.25
0.25

julia> OnlineStats.cdf(o, 1.001) # expect very close to but > 0.25
0.00066633333333326

julia> OnlineStats.cdf(o, 2.0) # expect 0.5 or very close to it
0.3333333333333333

julia> OnlineStats.cdf(o, 2.999) # expect very close to but < 1.0
1.165667

julia> OnlineStats.cdf(o, 3.0)
1.0
```

So it still violates fundamental invariants and is not "smooth" over the range covered.

**Comment by joshday** [comment]
Okay, I think it's just a bug in the denominator.  I'll look into it.

**Comment by joshday** [comment]
I've decided to rely on `StatsBase.ecdf` here rather than re-implement the same logic, so now your original example is (on master)

```julia
julia> o = OnlineStats.KHist(2)
KHist: n=0 | value=(x = Union{Float64, Int64}[], y = Union{Float64, Int64}[])

julia> fit!(o, [1,1,2])
KHist: n=3 | value=(x = [1.0, 2.0], y = [2, 1])

julia> f = ecdf(o)
ECDF{Array{Float64,1},Weights{Int64,Int64,FrequencyWeights{Int64,Int64,Array{Int64,1}}}}([1.0, 2.0], [2, 1])

julia> f(1)
0.6666666666666666
```
