### ISSUE TITLE
Online PCA algorithms?

### ISSUE THREAD

**Issue by robertfeldt** [joshday/OnlineStats.jl#189]
Would this be of interest to implement? I have a need for one and have looked around but here doesn't seem to be fast implementations in Julia of some, good approximate ones like CCIPCA (Candid Covariance-free IPCA). If there is interest I can add it as a PR? If so, any special ideas on API since there is a difference between "fitting" new vectors and projecting them into the reduced space. Is there preferred API/naming also for the latter, algorithm-specific things? I was thinking an interface maybe like:

```
using OnlineStats

ccipca = OnlineStats.CCIPCA(2, 1000; l=3) # We want 2D projections of 1000-element vectors and with an amnesic factor, l, of 3 (defaults to 1, i.e. assumes stationary distribution)
fit!(ccipca, [rand(1000) for _ in 1:1000]) # Each value added is a Vector{Float64} of length 1000

# Rest of interface stays close to normal PCA in Julia, see https://multivariatestatsjl.readthedocs.io/en/stable/pca.html
@assert indim(ccipca) == 1000
@assert outdim(ccipca) == 2
@assert size(mean(ccipca)) == (1000, )
@assert size(projection(ccipca)) = (2, 1000) # Projection matrix
```

**Comment by robertfeldt** [comment]
Oh, yeah I forgot that probably also good to have `transform` and `reconstruct` methods which does the into/out-from projections without the user needing to do it manually (continuing the code from above):

```
x = rand(1000)
xp = transform(ccipca, x) # Project x into the space (does not change the projection matrix)
xhat = reconstruct(ccipca, xp) # Tries to reconstruct x from the projected vector
```
As a convenience it might then be nice to also have (since this is a common use case):
```
xp2 = fittransform!(ccipca, x) # First fits x and then projects it
```
Feedback on this propose API is welcome.

**Comment by joshday** [comment]
Looks cool!  A PR would be great.  API makes sense to me too.  Looks like StatsBase has `transform` and `reconstruct`, but not `indim` and `outdim`.  I'd rather not add a MultivariateStats dependency, but I can live with the name clashes.

Note you could also run something like `MultivariateStats.pcacov` after fitting an `OnlineStats.CovMatrix`.  I've been meaning to add that for a while.

**Comment by joshday** [comment]
Or maybe `indim` and `outdim` are unnecessary and can be replaced with `size`?

**Comment by robertfeldt** [comment]
Thanks @joshday for your input. Ok, yes `size` sounds better than having both indim and outdim. I don't plan to have a dependence on MultiVariate Stats, I plan to implement CCIPCA from scratch for OnlineStats. To be fast it doesn't calculate a cov-matrix at all.

Did you mean that `StatsBase` has a PCA? I haven't found it so might still be nice to have the indim and outdim methods for people coming from `MultivariateStats` and switching to an online version in OnlineStats...

**Comment by joshday** [comment]
> Did you mean that StatsBase has a PCA?

No, just saying that we can use some of the same names as MultivariateStats (transform and reconstruct) without clashing names since they come from StatsBase

**Comment by joshday** [comment]
I'm fine with having unexported `indim` and `outdim` so we match MultivariateStats.  Maybe add to the docstring that those methods exist.

**Comment by robertfeldt** [comment]
@joshday it is now implemented in my fork and with tests added. Do you want to review it here first:

https://github.com/robertfeldt/OnlineStats.jl/commit/10264f3f07a41f4ce21584d7608400e64e2d6dea

or you prefer if I do the PR and then you review it?

**Comment by robertfeldt** [comment]
Ok, I now fixed the docstring which had the arguments in a different order:

https://github.com/robertfeldt/OnlineStats.jl/commit/eec857c8cf6f097b3d981f9f01eb6e30627c9149

**Comment by robertfeldt** [comment]
I wonder if we can export the `transform` method since it is probably the main reason someone would like to use CCIPCA. So requiring them to explicitly include it might be awkward. While `reconstruct` will be much less common so ok not to export imho.

**Comment by robertfeldt** [comment]
Ok, I added better docstrings and refactored the tests so I think this is not pretty solid. Please take a look and then I can submit PR if you think it looks fine, here are the main two files added:

[src/stats/pca.jl](https://github.com/robertfeldt/OnlineStats.jl/blob/master/src/stats/pca.jl)
[test/test_ccipca.jl](https://github.com/robertfeldt/OnlineStats.jl/blob/master/test/test_ccipca.jl)

I should have done this in a branch on my fork but missed that when I started... ;)

**Comment by robertfeldt** [comment]
Hmm, I just realized the transform and reconstruct should probably also rescale by the eigenvalues. I guess it will not really matter since that is just a general scaling of the whole space so will not affect visualisations.

**Comment by joshday** [comment]
> or you prefer if I do the PR and then you review it?

Yeah, that'll be easier to make comments/suggestions on specific things, but I like the look of things so far!

> I wonder if we can export the transform method

Alternatively we could make `CCIPCA` callable, so that `ccipca(x)` does the transform.  I'm also okay with exporting `transform`.

**Comment by robertfeldt** [comment]
Ok, added callable (on CCIPCA objects) but didn't export `transform`. I prefer to export it. Comments welcome!

https://github.com/joshday/OnlineStats.jl/pull/190

**Comment by robertfeldt** [comment]
This has now been merged so closing. Thanks for a good collab on this.
