### ISSUE TITLE
heatmap has axes swapped

### ISSUE THREAD

**Issue by jstrube** [joshday/OnlineStats.jl#193]
Consider the following example. It creates a HeatMap of a 2D Gaussian distribution.
The distribution is centered on (1.0, 0), but the plot is centered on (0, 1.0)
I'm seeing this in v1.0.2 and v1.2.0, both with Julia v1.4.1.
```
o = fit!(HeatMap(-5:.1:5, -5:.1:5), zip(1.0. + randn(10^6), randn(10^6)))

using Plots
plot(o)
```

**Comment by jstrube** [comment]
There's something weird going on here. I've tried swapping x and y, but that doesn't seem to make it better.
I think there's some transposition being applied where it shouldn't, or something like that.
It almost looks like the histogram is computed correctly, but then the plot is transposed.

**Comment by joshday** [comment]
Ah, good catch.  It was being transposed.  Fixed on master.
