### ISSUE TITLE
Window functions?

### ISSUE THREAD

**Issue by tbreloff** [joshday/OnlineStats.jl#20]
This departs only slightly from the spirit of OnlineStats, but sometimes it's useful to have statistics on a rolling window.  (mean/variance/high/low over the last 30 periods, for example)  We could require QuickStructs.jl (one of my packages) to use the `CircularBuffer` to store the required history, or there's probably another implementation elsewhere if you don't want to add a dependency.  This may be too big a change... need to think on it more.

Separately, I also have a `RollingWindow` type in QuickStructs that will hold a window of data given pre-specified lags, and could make various time-series modelling a little nicer (ARMA, VARMA, VECM, etc)

**Comment by joshday** [comment]
Taking a look at open issues and realized I never commented on this.  Window functions would be great!  I need to take a look at QuickStructs.

**Comment by joshday** [comment]
An `AbstractSeries` subtype could handle this.  See https://github.com/joshday/OnlineStats.jl/pull/74

**Comment by joshday** [comment]
OnlineStats now has a `MovingWindow` type that satisfies this for now.
