### ISSUE TITLE
How to remove observations?

### ISSUE THREAD

**Issue by JockLawrie** [joshday/OnlineStats.jl#201]
Hi there,

Thanks for this package - it's awesome.

I'm doing some agent-based modelling and wanting to use `OnlineStats` to keep track of various metrics as the simulation proceeds. Suppose I have 1,000,000 agents and that each agent has a colour, one of red, green or blue. At each time step I want to count the number of agents by colour.

Option 1 is to iterate over the vector of agents, updating a `CountMap` as this proceeds.

But at each time step, only some of the agents are updated, so it'd be more efficient to update the `CountMap` using only the updated agents. For example, an agent's colour may have changed from red to blue. To do this would require, for each updated agent, removing the old value (red) from the statistic and appending the new value (blue) to the statistic.

Of course the 2nd operation exists - `fit!(stat, newvalue)`.
Could a removal operation be implemented, something like `unfit!(stat, oldvalue)`?

The same removal operation could also be used when agents are removed from the simulation.

Cheers,
Jock

**Comment by JockLawrie** [comment]
…the efficiency gained may seem small, but adds up over 1000s of complex simulations.

**Comment by joshday** [comment]
> Thanks for this package - it's awesome.

Thanks for the kind words!

---

Hmm, in general `unfit!` isn't possible, but there's probably quite a few use cases where it makes sense for `CountMap`.  I just added a `delete!` method in OnlineStatsBase master.  Is that sufficient for your use case?

```Julia
julia> o = fit!(CountMap(Char), rand("ABCD", 1000))
CountMap: n=1000 | value=OrderedCollections.OrderedDict('C'=>254,'A'=>227,'B'=>248,'D'=>271)

julia> delete!(o, 'A')
CountMap: n=773 | value=OrderedCollections.OrderedDict('C'=>254,'B'=>248,'D'=>271)
```

**Comment by joshday** [comment]
Or are you trying to decrement the count of a level by 1?

**Comment by JockLawrie** [comment]
Thanks for the prompt response, and the quick fix...
but I'm just trying to decrement 'A' by 1.
Could this be achieved in the general case by fitting an observation with a negative weight?

**Comment by joshday** [comment]
Okay, I could add a `fit!(::CountMap{T}, ::Pair{T, Int})` method that changes the count by the second value of the pair.

**Comment by joshday** [comment]
On OnlineStatsBase master:

```julia
julia> o = fit!(CountMap(String), ["A" => 10, "B" => 11])
CountMap: n=21 | value=OrderedCollections.OrderedDict("A"=>10,"B"=>11)

julia> fit!(o, "B" => -5)
CountMap: n=16 | value=OrderedCollections.OrderedDict("A"=>10,"B"=>6)
```

I'll get a release out soon/today.
