### ISSUE TITLE
Initialization of `Quantile`

### ISSUE THREAD

**Issue by jangevaare** [joshday/OnlineStats.jl#204]
Hello, I get the following error when initializing a `Quantile`, the issue more specifically is with the `show` method when the `Quantile` has yet to be `fit!` to any values. I'm on `v1.5.1`.

```
julia> Quantile()
Quantile: n=0 | value=Error showing value of type Quantile{ExpandingHist{Number,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}}:
ERROR: ArgumentError: quantile of an empty array is undefined
```

**Comment by joshday** [comment]
Ah, thanks for reporting.  I rewrote `Quantile` last week and apparently broke `value` for when nobs is 0.  Fixed on master, new release out in a moment.
