### ISSUE TITLE
NaN handling

### ISSUE THREAD

**Issue by jangevaare** [joshday/OnlineStats.jl#205]
I think the only bug is with `Quantile` (see below), but behaviour with variance I found interesting as well. I wonder if in general there is a more appropriate way to represent values of OnlineStats that have insufficient sample size to calculate.
```
julia> fit!(Mean(), NaN)
Mean: n=1 | value=NaN

julia> fit!(Variance(), NaN)
Variance: n=1 | value=1.0

julia> fit!(Variance(), [NaN, NaN])
Variance: n=2 | value=NaN

julia> fit!(Quantile(), NaN)
ERROR: ArgumentError: start and stop must be finite, got NaN and NaN
```

**Comment by joshday** [comment]
Hmm, `Variance` should check for `isfinite` rather than just return 1 there.  Fixed in OnlineStatsBase master.

---

For `Quantile`, I'm okay with an error since that's what base Julia does:

```Julia
julia> quantile([NaN],.5)
ERROR: ArgumentError: quantiles are undefined in presence of NaNs
```

However, I can make the OnlineStats error a little less cryptic.
