### ISSUE TITLE
HyperLogLog algorithm used and paper link

### ISSUE THREAD

**Issue by brucala** [joshday/OnlineStats.jl#208]
https://github.com/joshday/OnlineStats.jl/blob/e554858134f38b3e22499b2de1e4be2e5eab3c67/src/stats/stats.jl#L233

From the link in the documentation regarding HyperLogLog, I would conclude that the improved `HyperLogLog++` is used (pseudocode in figure 6), which is the algorithm proposed in the paper. However, I understand from the code that the algorithm that is actually being implemented is the original  `HyperLogLog` (pseudocode in figure 1 and reference [7] in the cited paper). 

It'd be awesome if `HyperLogLog++` could be implemented instead (see figure 8 in the paper for a comparison of the relative errors of the two algorithms). But in the meantime I think it'd be fair to clarify in the documentation what algorithm is indeed being used.

Thanks (again) for the wonderful OnlineStats!

**Comment by StefanKarpinski** [comment]
I believe this estimator is strictly better than HyperLogLog++ at all ranges of values: https://github.com/joshday/OnlineStats.jl/issues/177

**Comment by brucala** [comment]
I had a look at the paper and indeed it looks awesome. Apparently it's not only strictly better at all ranges, but it's also elegant in the sense that it tackles the problem from the root and it doesn't use any empirical ad hoc corrections.
I'll be at least one week offline now, but when I'm back I'd like to try my first contribution to OnlineStats with an implementation of it.

**Comment by brucala** [comment]
I believe this issue can also be closed after #177
