### ISSUE TITLE
Documentation out of date?

### ISSUE THREAD

**Issue by baggepinnen** [joshday/OnlineStats.jl#211]
I can't find `L2Penalty` which is mentioned here 
https://joshday.github.io/OnlineStats.jl/stable/api/#OnlineStats.LinRegBuilder

It seems `prox` is only defined for `abs, abs2`.

**Comment by joshday** [comment]
Ah, yes that's out of date.  Fixed on master.  I removed some dependencies (LearnBase/LossFunctions/PenaltyFunctions) a few months back.
