### ISSUE TITLE
Docs say `Hist(::Int)` should work.

### ISSUE THREAD

**Issue by shashi** [joshday/OnlineStats.jl#214]
But I get

```
MethodError: no method matching Hist(::Int64)
Closest candidates are:
```

**Comment by joshday** [comment]
Are you looking at `KHist` docs, rather than `Hist`?

https://joshday.github.io/OnlineStats.jl/stable/api/#OnlineStats.Hist

https://joshday.github.io/OnlineStats.jl/stable/api/#OnlineStats.KHist

**Comment by shashi** [comment]
Oh damn. Google for `OnlineStats.jl histogram` lead straight to https://joshday.github.io/OnlineStats.jl/v0.15.0/api.html. Sorry! Thanks!!

**Comment by joshday** [comment]
Of course Google sends you to the docs from (checks notes) 13 releases ago
