### ISSUE TITLE
Must the datum be iterable?

### ISSUE THREAD

**Issue by yakir12** [joshday/OnlineStats.jl#226]
When fitting a thing that lacks an iterate method, I get an error.

Consider the following example with colors:
```julia
using OnlineStats, ColorTypes

colors = rand(Gray, 10)

μ = Mean()
fit!(μ, colors[1])
fit!(μ, colors)

μ = FTSeries(Mean(); transform = Float64)
fit!(μ, colors[1])
fit!(μ, colors)
```
All 4 fits result in:
```julia
ERROR: MethodError: no method matching iterate(::Gray{Float64})
```
(note that `ColorVectorSpace` doesn't alleviate this)

So the question is, should:
1. OnlineStats allow for fitting datum that isn't iterable (i.e. an element, not a collection)
2. ColorTypes add a iterate method
3. nothing change cause this should error as it does
4. something else...?

**Comment by joshday** [comment]
Option 4!

I think you just need something like `FTSeries(Colorant, Mean(); transform = Float64)`.

# Longer Explanation

The way `fit!(::OnlineStat{T}, data::S)` works is that if:

- `S == T`: Update with single observation (`OnlineStatsBase._fit!`)
- `S != T`: Iterate through `data` and `fit!` each item.

Looking at super types:
```
# Mean()
OnlineStat{Number}

# FTSeries(Mean(); transform=float)
OnlineStatsBase.StatCollection{Union{Missing, Number}}

# FTSeries(Colorant, Mean(); transform=float)
OnlineStatsBase.StatCollection{Union{Missing, Colorant}}
```

Thus, for `Mean()` and `FTSeries(Mean(); transform=float)`, fitting a `Gray` will result in OnlineStats trying to iterate it.

But `FTSeries(Colorant, Mean(); transform=float)` tells OnlineStats that the type of a single observation is `Colorant`.

---

Side note: The `Union{Missing, T}` stuff for `FTSeries` is that I was thinking filtering out missing data was the main use case.  I'm going to change this.  The union shouldn't be added automatically.

**Comment by yakir12** [comment]
Thank you!
