### ISSUE TITLE
Is it possible to compute stats grouped by a column?

### ISSUE THREAD

**Issue by xiaodaigh** [joshday/OnlineStats.jl#231]
The current `GroupBy` accepts a type. But is it possible to say, I have data coming in that is of the form `(grp, x, y)` And I wish to compute the same stats for `x` and `y` but I create a set of stats for each distinct value of `grp`?

Like a group by statement in SQL?

```
select
  mean(x),
  mean(y),
from
  data
group by
  grp;
```

**Comment by joshday** [comment]
If I'm understanding correctly, you would use a `Series` as the stat in your `GroupBy`:

```
GroupBy(typeof(grp), Series(Mean(), Mean()))
```

**Comment by xiaodaigh** [comment]
Ok. what if `grp` and `x` have the same type? Or something like that. Or I need to wrap grp in its own type.
