### ISSUE TITLE
Documentation hard to read with Chrome in DarkMode

### ISSUE THREAD

**Issue by olemaiwald** [joshday/OnlineStats.jl#232]
Hi all,

when reading the Documentation in DarkMode, the Code parts are very hard to read because they are nearly black.

I do not really know how, but I assume this could be a rather quick fix.

<img width="1172" alt="Bildschirmfoto 2021-07-22 um 15 41 57" src="https://user-images.githubusercontent.com/53152691/126648899-f36c0f66-e02a-40b3-8b35-891f8be8c103.png">

**Comment by joshday** [comment]
It's fixed on master, so you can change the version in the bottom left to "dev".  I'll get a new release out soon.
