### ISSUE TITLE
Gaussian Filters i.e. Kalman Filters

### ISSUE THREAD

**Issue by p-casgrain** [joshday/OnlineStats.jl#233]
I think that Gaussian Filters are a super useful class of online statistics. It would be really nice to add these to the OnlineStats.jl roster.

I've spotted [GaussianFilters.jl](https://github.com/sisl/GaussianFilters.jl) as a potential candidate for a backend. Using this package we can define some sort of class `OnlineGaussianFilter <: OnlineStat` which stores a `GaussianBelief` (the state) and an `AbstractFilter ` (the model). The `_fit!` function can just rely on the `update` method that this package implements for the various implementations of `AbstractFilter`.

**Comment by joshday** [comment]
If the package authors of GaussianFilters want to work with OnlineStats, the solution would be for them to depend on OnlineStatsBase.
