### ISSUE TITLE
Count statistic

### ISSUE THREAD

**Issue by krynju** [joshday/OnlineStats.jl#238]
So with the DTable in Dagger i can do this 
```julia
julia> d = DTable((a=1:100,), 10)
DTable with 10 partitions
Tabletype: NamedTuple

julia> fetch(reduce(fit!, d, init=Mean()))
(a = Mean: n=100 | value=50.5,)
```

Inside that reduce the reduction first happens per partition and then all 10 results get merged into the final result.

This works super well on the OnlineStats structures, because for the reductions inside the partitions it works as usual and then it also uses fit! to merge the statistics in the final step (user doesn't have to define 2 different functions for reduction) (thanks to this https://github.com/joshday/OnlineStatsBase.jl/pull/26)

I want to do something similiar, but just to count the number of rows. I can implement a struct like this in Dagger, but I guess OnlineStats would be a better place to have it.

Something like this:

```julia
fetch(reduce(fit!, d, init=Count()))
(a = Count: n=100)
```

It's not really a statistic I guess, but it would simplify the usage of DTable a lot if someone wanted to get a count using reduce
I know there's better ways of getting that result like just calling length properly, but this just seems elegant 🤷‍♀️

Let me know what you think!

**Comment by krynju** [comment]
Hey, that's awesome!

What do you think about having the default behavior as T=Not(Counter)?
So it would count everything by default and by setting the type explicitly you would limit the type as you have it right now

**Comment by joshday** [comment]
Since it's easy to set `T`, I don't think it's worth changing the default and potentially breaking things.
