### ISSUE TITLE
Ensure consistent interface

### ISSUE THREAD

**Issue by tbreloff** [joshday/OnlineStats.jl#24]
I've noticed in one or two places the update! function is defined differently... sometimes it's `update!(o, x, y)` and sometimes `update!(o, y, x)`.  There might be similar things for other methods... need to check.  This all may be my fault, but we should pick one and make sure everything conforms.

**Comment by joshday** [comment]
I've tried to consistently use `update!(o, x, y)`.  This follows R's (and GLM.jl's) syntax for things like `lm(x, y)`.  I'm not sure how the formula stuff from DataFrames works, but some users might also want `update(o, y ~ x)`.

**Comment by tbreloff** [comment]
Ok sounds good.. I'll fix anything I find to put the x before the y.

**Comment by tbreloff** [comment]
fixed in commit 2e33355
