### ISSUE TITLE
Bug: Counter T does not work with abstract types like Any

### ISSUE THREAD

**Issue by schlichtanders** [joshday/OnlineStats.jl#242]
Using Counter I was very surprised that `Counter(Any)` does not work.

Given the documentation `Count the number of items in a data stream with elements of type T.` this sounds like a but, as every element is of type `Any`.

**Comment by schlichtanders** [comment]
Hi JoshDay, thank you for managing these tickets.

I actually found the misunderstanding
```
julia> o = Counter(Any)
Counter: n=0 | value=0

julia> fit!(o, [1,2,3,4])
Counter: n=1 | value=1
```
Any is also matching iterators, which makes totally sense.
The workaround is iterating yourself.

**Comment by joshday** [comment]
Ah, right!  Glad you worked it out.
