### ISSUE TITLE
OnlineStats.variation function mentioned in docs but no longer available

### ISSUE THREAD

**Issue by schlichtanders** [joshday/OnlineStats.jl#243]
[online PCA](https://joshday.github.io/OnlineStats.jl/latest/api/#OnlineStats.CCIPCA) mentions `OnlineStats.variation` however that does not exist any longer.

What is the current alternative?

**Comment by joshday** [comment]
@robertfeldt just to confirm, `variation` was renamed to `relativevariances`?

**Comment by robertfeldt** [comment]
Yes, that is correct. I don't remember our reasoning for the rename but, yes, we did it. ;)

So the documentation should be changed but nothing else.
