### ISSUE TITLE
Remove dependency on DataFrames?

### ISSUE THREAD

**Issue by joshday** [joshday/OnlineStats.jl#25]
I'm concerned that the methods that depend on DataFrames (`tracedata` stuff) aren't particularly useful to people that aren't me ( I'm using it to generate plots for my dissertation). 

I think `tracedata` can/should be replaced with a function that generates `Vector{T <: OnlineStat}` instead of a DataFrame.

Any objections?

**Comment by tbreloff** [comment]
I'm not using it right now, so it's not a big deal to me.  I will note that I've been brainstorming on some ways that we could make it easier to "connect" different intermediate results to outside data flows (sharing online variances, or plotting, or some other stuff).  I think the Reactive stuff would be cool if we had a fully-fleshed-out integration, but I'm a little skeptical that we'll get there.  For now, removing tracedata is fine with me.

**Comment by joshday** [comment]
Sounds good.  I've removed it.  I think we could do some really cool stuff with Reactive.  I'll look into that a bit more.
