### ISSUE TITLE
Julia VS Code extension reports "Possible method call error" for `fit!`

### ISSUE THREAD

**Issue by Yue-Zhengyuan** [joshday/OnlineStats.jl#268]
I write the following small program to ask input numbers from user, and calculate the mean and variance. 

```julia
using OnlineStats

function calculate_average()
    o = Series(Mean(), Variance())
    println(typeof(o))
    i = 0
    while true
        println("Enter number or 'q' to quit:")
        input = readline()
        if input == "q"
            break
        else
            x = parse(Float64, input)
            fit!(o, x)
            i += 1
            println(value(o))
        end
    end
end

calculate_average()
```

But the Julia VS Code extension reports "Possible method call error" at `fit!(o, x)`. It thinks `fit!` as `StatsAPI.fit!`, and reports it is a "function with 0 methods"

----

System information:

- OnlineStats: 1.6.3
- VS Code: 1.84.2
- Julia extension: 1.60.2
- Julia: 1.9.4
- OS: macOS 14.0

**Comment by joshday** [comment]
My system looks just like yours, but I can't reproduce this.

**Comment by adknudson** [comment]
I often run into a similar issue, and can fix it by explicitly importing the `fit!` method

```julia
using OnlineStats
using OnlineStats: fit!
```

I think the issue usually comes from using extended methods, i.e. because `fit!` is imported/owned by `StatsBase`. Seems to be a general limitation of the VSCode extension.
