### ISSUE TITLE
Extract field of an observation before feeding an OnlineStats - ValueExtractor wrapper

### ISSUE THREAD

**Issue by femtotrader** [joshday/OnlineStats.jl#271]
Hello,

I'm looking for a way to wrap a function which could extract a field of an observation and feed its value to a OnlineStat object. 

I found in OnlineStats doc `CallFun` which call `f(o)` each time an observation `data` is being updated but what I'm looking for is exactly the opposite: call `f(data)`, feed `f(data)` to `o`
I'm aware I can directly do `fit!(o, f(data)` but I want to do `fit!(wrapped_o, data)` where `wrapped_o` contains both OnelineStat `o` and function `f`

Does such a wrapper exists in OnlineStats? (or in OnlineStatsBase)
If not how can it be implemented?

My use case:

I want to wrap the [EMA indicator](https://github.com/femtotrader/IncTA.jl/blob/main/src/indicators/EMA.jl) in a `ValueExtractor` object with a function like `candle -> candle.close`
Something like

```julia
ema = EMA{Float64}(period=ma_period)
o = ValueExtractor{OHLCV{Missing,Float64,Float64}}(ema, candle -> candle.close)
```

Kind regards

**Comment by joshday** [comment]
See https://joshday.github.io/OnlineStats.jl/latest/api/#OnlineStatsBase.FilterTransform

I meant to split out `Filter` and `Transform` as separate wrappers but I guess I never got around to it.

**Comment by femtotrader** [comment]
Thanks @joshday
