### ISSUE TITLE
ExtremeValues doesn't work

### ISSUE THREAD

**Issue by LexaLutyi** [joshday/OnlineStats.jl#274]
Hi!

I'm using probably new feature: `ExtremeValues`, and I think it doesn't work:

```julia
extr = OnlineStats.ExtremeValues(Int)
fit!(extr, [1, 1, 1])
# ExtremeValues: n=3 | value=(lo = [1=>1, 1=>1, 1=>1], hi = [1=>1, 1=>1, 1=>1])
```

I expect
```
# ExtremeValues: n=3 | value=(lo = [1=>3], hi = [1=>3])
```

Do I miss something? Or is it not implemented yet?

Thank you!

**Comment by joshday** [comment]
Ah, looks like a bug/uncovered edge case.
