### ISSUE TITLE
Odd interaction of `Group` with broadcast

### ISSUE THREAD

**Issue by adienes** [joshday/OnlineStats.jl#275]
this was a little unexpected to me, as ordinarily `foo.(x)` is equivalent to `map(foo, x)`

```
julia> g = Group(Mean(), Variance())
Group
├─ Mean: n=0 | value=0.0
└─ Variance: n=0 | value=1.0


julia> value.(g)
(Mean: n=0 | value=0.0, Variance: n=0 | value=1.0)

julia> map(value, g)
2-element Vector{Float64}:
 0.0
 1.0
```

**Comment by joshday** [comment]
I'm more surprised that `map(value, g)` works here, actually.  The following method is in OnlineStatsBase, so `OnlineStat`s opt out of the broadcast stuff:

```julia
Broadcast.broadcastable(o::OnlineStat) = Ref(o)
```

According to git blame, I apparently accepted a PR from someone 4 years ago (!) that added it.  I don't know the reason, but there must have been one for adding it.  At this point I think it's too breaking to remove it.

**Comment by adienes** [comment]
ok, thanks for the explanation
