### ISSUE TITLE
[speculative] `NullStat`

### ISSUE THREAD

**Issue by adienes** [joshday/OnlineStats.jl#276]
I have some use cases where I might pass in any arbitrary `OnlineStat` type; occasionally I want this to be a no-op but not change the signature of the function

any receptiveness to adding a `NullStat` where `fit!(::NullStat, x)` simply does nothing?

just an idea

**Comment by joshday** [comment]
Seems a bit niche to add to the package, but it's pretty easy to do yourself:

```Julia
import OnlineStatsBase: OnlineStat, _fit!, nobs, value
struct NullStat <: OnlineStat{Any} end 
value(::NullStat) = nothing 
nobs(::NullStat) = 0
_fit!(::NullStat, x) = nothing
```

```Julia
julia> using OnlineStats

julia> fit!(NullStat(), randn(100))
NullStat: n=0 | value=nothing
```
