### ISSUE TITLE
fix 0.4 deprecation warnings

### ISSUE THREAD

**Issue by tbreloff** [joshday/OnlineStats.jl#28]
There's a bunch, here are some examples:

```
WARNING: [a,b,...] concatenation is deprecated; use [a;b;...] instead
 in depwarn at ./deprecated.jl:62
 in oldstyle_vcat_warning at ./abstractarray.jl:29
 in anonymous at /home/tom/.julia/v0.4/OnlineStats.jl/test/analyticalpca_test.jl:24
 in facts at /home/tom/.julia/v0.4/FactCheck/src/FactCheck.jl:315
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:133
 in include at ./boot.jl:254
 in include_from_node1 at loading.jl:133
 in process_options at ./client.jl:306
 in _start at ./client.jl:406
while loading /home/tom/.julia/v0.4/OnlineStats.jl/test/analyticalpca_test.jl, in expression starting on line 5
```

```
WARNING: float64(x) is deprecated, use Float64(x) instead.
 in depwarn at ./deprecated.jl:62
 in float64 at deprecated.jl:49
 in _kmeans! at /home/tom/.julia/v0.4/Clustering/src/kmeans.jl:156
 in kmeans! at /home/tom/.julia/v0.4/Clustering/src/kmeans.jl:37
 in kmeans at /home/tom/.julia/v0.4/Clustering/src/kmeans.jl:53
 in emstart at /home/tom/.julia/v0.4/OnlineStats.jl/src/distributions/offlinenormalmix.jl:19
 in anonymous at /home/tom/.julia/v0.4/OnlineStats.jl/test/normalmix_test.jl:13
 in context at /home/tom/.julia/v0.4/FactCheck/src/FactCheck.jl:341
 in anonymous at /home/tom/.julia/v0.4/OnlineStats.jl/test/normalmix_test.jl:8
 in facts at /home/tom/.julia/v0.4/FactCheck/src/FactCheck.jl:315
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:133
 in include at ./boot.jl:254
 in include_from_node1 at loading.jl:133
 in process_options at ./client.jl:306
 in _start at ./client.jl:406
while loading /home/tom/.julia/v0.4/OnlineStats.jl/test/normalmix_test.jl, in expression starting on line 7
```

```
WARNING: int(x::AbstractArray) is deprecated, use round(Int64,x) instead.
 in depwarn at ./deprecated.jl:62
 in int at deprecated.jl:49
 in anonymous at /home/tom/.julia/v0.4/OnlineStats.jl/test/logreg_test.jl:17
 in context at /home/tom/.julia/v0.4/FactCheck/src/FactCheck.jl:341
 in anonymous at /home/tom/.julia/v0.4/OnlineStats.jl/test/logreg_test.jl:9
 in facts at /home/tom/.julia/v0.4/FactCheck/src/FactCheck.jl:315
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:133
 in include at ./boot.jl:254
 in include_from_node1 at loading.jl:133
 in process_options at ./client.jl:306
 in _start at ./client.jl:406
while loading /home/tom/.julia/v0.4/OnlineStats.jl/test/logreg_test.jl, in expression starting on line 8
```

```
WARNING: [a] concatenation is deprecated; use collect(a) instead
 in depwarn at ./deprecated.jl:62
 in oldstyle_vcat_warning at ./abstractarray.jl:29
 in anonymous at /home/tom/.julia/v0.4/OnlineStats.jl/test/logreg_test.jl:15
 in context at /home/tom/.julia/v0.4/FactCheck/src/FactCheck.jl:341
 in anonymous at /home/tom/.julia/v0.4/OnlineStats.jl/test/logreg_test.jl:9
 in facts at /home/tom/.julia/v0.4/FactCheck/src/FactCheck.jl:315
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:133
 in include at ./boot.jl:254
 in include_from_node1 at loading.jl:133
 in process_options at ./client.jl:306
 in _start at ./client.jl:406
while loading /home/tom/.julia/v0.4/OnlineStats.jl/test/logreg_test.jl, in expression starting on line 8
```

**Comment by joshday** [comment]
It's probably about time for me to start using v0.4.  I'll start cleaning some of this up.

**Comment by tbreloff** [comment]
I'll include this here as it's not necessarily wrong/buggy but might as well be changed.  In a few places you have type assertions that are redundant like:
```
    n::Int = length(y)
    nj::Int = length(o.components)  # number of components
    π::VecF = probs(o)
    μ::VecF = means(o)
    σ::VecF = stds(o)

    w::MatF = zeros(n, nj)
    wy::MatF = zeros(n, nj)
    s1::VecF = zeros(nj)
    s2::VecF = zeros(nj)
    s3::VecF = zeros(nj)
```

which is exactly equivalent to:
```
    n = length(y)
    nj = length(o.components)  # number of components
    π = probs(o)
    μ = means(o)
    σ = stds(o)

    w = zeros(n, nj)
    wy = zeros(n, nj)
    s1 = zeros(nj)
    s2 = zeros(nj)
    s3 = zeros(nj)
```

Do you care if I remove some of the assertions that aren't necessary?

**Comment by joshday** [comment]
I was under the impression that declaring the type was beneficial to the compiler in some way.  I'd much rather have the cleaner code.  I don't mind at all.

**Comment by tbreloff** [comment]
It should be the same:
```
julia> f(x) = (y::Int = x; y)
f (generic function with 1 method)

julia> @code_native f(1)
        .text
Filename: none
Source line: 1
        pushq   %rbp
        movq    %rsp, %rbp
Source line: 1
        movq    %rdi, %rax
        popq    %rbp
        ret

julia> g(x) = (y = x; y)
g (generic function with 1 method)

julia> @code_native g(1)
        .text
Filename: none
Source line: 1
        pushq   %rbp
        movq    %rsp, %rbp
Source line: 1
        movq    %rdi, %rax
        popq    %rbp
        ret
```

**Comment by joshday** [comment]
Yeah, I know for that example Julia compiles a new method for each type you give to `g()`, but I thought there would be some benefit for variables defined in the function's scope.

**Comment by tbreloff** [comment]
I just installed julia 0.3.10 for testing.  I've got a "cleanup" branch which i'll try to handle the depr warnings and AbstractArray conversions, and test on 0.3 and 0.4.

**Comment by joshday** [comment]
How would you feel about changing our workflow a bit?  Currently, I just arbitrarily pull stuff into master from my branch from time to time.  I say we start using pull requests so that we can hold discussions about adding specific functionality.  

For instance, when I added `onlinefit!` and `tracefit!`, I should've made a pull request so you could weigh in any thoughts to the function names and such.

**Comment by tbreloff** [comment]
I think that's a good idea in general, but it may be a little heavy-handed for now.  The criteria for merging into master should be that it passes our tests on both 0.3 and 0.4.  If there's a breaking change we could/should get in the habit of tagging specific commits on the master branch (which we'll need for registering in metadata) and updating the REQUIRE files for any downstream dependencies that we know about (don't worry about this yet).  Lets wait until we get through one more round of cleanup and documentation and then we can put some more organized workflow in place.  I think we're a week or two from "announcing" the package officially.  How do you feel about that?

**Comment by joshday** [comment]
Okay, that sounds good to me.  

Yeah, I'm working on bootstrap stuff today.  Once I get through that and fill out some documentation I'll feel pretty good about announcing.

**Comment by tbreloff** [comment]
I've been doing a ton of cleanup, but we're going to have to do a focused merge of everything since it's been a while since we branched from the same commit (and I've touched basically every file).  Let me know when you have a stable version of what you're working on and I'll try to merge without losing either of our updates.  If you approve, then you should fast-forward (i.e. merge mine just after I finish merging yours) so we start from the same commit again.

**Comment by joshday** [comment]
Now would actually be a good time.  Today I only touched bootstrap.jl and some docs

**Comment by tbreloff** [comment]
Tests are passing!  I tagged the current commit at v0.1.0.
