### ISSUE TITLE
Support `keys` and `values` on `GroupBy`

### ISSUE THREAD

**Issue by schlichtanders** [joshday/OnlineStats.jl#282]
GroupBy presents itself as a dictionary-like object. Also indexing works.
Hence supporting `keys` and `values` makes sense

**Comment by joshday** [comment]
Since `value(::GroupBy)::OrderedDict`, I don't think I'll add this.  An `OnlineStat` is an `OnlineStat`; I don't want to make any promises beyond that.  I partially regret adding some of the convenience methods like `mean(::Mean)`.
