### ISSUE TITLE
Bug: Y-Marginals for heatmap are wrong

### ISSUE THREAD

**Issue by schlichtanders** [joshday/OnlineStats.jl#283]
Even the documentation itself shows this
https://joshday.github.io/OnlineStats.jl/latest/dataviz/#HeatMap

![](https://joshday.github.io/OnlineStats.jl/latest/dataviz/5c2caf0d.svg)

See how the one marginal appears empty. It is not empty actually, just the y-axis is completely wrong.

**Comment by joshday** [comment]
This is a Plots.jl bug (incorrectly setting ylims).  I've added a fix.
