### ISSUE TITLE
Documentation/Wiki

### ISSUE THREAD

**Issue by tbreloff** [joshday/OnlineStats.jl#29]
What's your final intention for documentation?  Should we try to use the `doc"""..."""` notation that they're moving towards in Base?  Lets pool those thoughts here...

**Comment by joshday** [comment]
Yes, I think that's the way to go.  Most functions don't need separate doc strings for each method (`update!`, etc.) and I think we should at least have a one-liner for each type, i.e.

```julia
doc"Track the means by column of input data, similar to `mean(x, 1)`"
type Means
    ...
end
```

In my branch, I trashed everything in doc/.  It was mostly outdated examples now, and I started working on long-form documentation for ReadTheDocs.  I'm not sure what level of technical details should be here and what level should show up in the REPL.  

What would you like to see?

**Comment by tbreloff** [comment]
It probably makes sense to have a few one-liners about the "verbs" like update!, etc, and also more detail on the types.  It would be ideal if we had sufficient docs throughout the code that got automatically compiled into a wiki.  It would also be good to give labels to functionality like "tested", "robust", "experimental", "fast", "accurate", etc.

**Comment by joshday** [comment]
I really like the labels idea, like that's something I'd like to see incorporated into all of Julia.

**Comment by joshday** [comment]
I'm working on new documentation using gh-pages and mkdocs.  I never got mathjax working correctly with readthedocs, but I got mkdocs up and running pretty easily.  

I don't like that there's two separate sources of documentation at the moment, but there's no link to the gh-pages docs yet.

Once we get an official Julia v0.4 release, I'd like to release a new OnlineStats version which can support plotting (https://github.com/joshday/OnlineStats.jl/issues/38) and then redirect the README link to the gh-pages doc.

**Comment by joshday** [comment]
[Here](http://joshday.github.io/OnlineStats.jl/) are the new docs thus far.  Comments welcome.

**Comment by joshday** [comment]
Main documentation is now in the README.  Examples and specifics on StatLearn are in the doc folder.
