### ISSUE TITLE
Function Names

### ISSUE THREAD

**Issue by joshday** [joshday/OnlineStats.jl#3]
While changes are being made, let's nail down some function names.

- `nobs(obj)`: return the number of observations used
- `state(obj)`: create a DataFrame in the form of `DataFrames.melt` 
- `addstate!(df, obj)`: append `state(obj)` to new row(s) in `df`
- `param(obj)`: return `Vector{Symbol}` of parameter names
- `value(obj)`: return simplest form of current estimate
- `tracedata(Stat, y, b)`: return DataFrame for making traceplot for statistic `Stat` on data `y` using batch size `b` 
- `onlinefit(Distribution, y)`: create object for online estimation of the parametric density `Distribution` using first batch `y`

**Comment by tbreloff** [comment]
Here's some thoughts:
- `nobs(obj)`: sounds good
- `state(obj)`: i'm still a little confused on this one.  if you just want a snapshot of the values, why not just call `values(obj)`?  If what you're really after is a constructor of a DataFrames object, then i think it makes more sense to explicitly define that constructor: `DataFrames.DataFrame(obj::Var)` which creates an empty df with the right columns, then optionally does `push!(df,obj)`
- `addstate!(df, obj)`: i *think* the more correct thing is to define: `Base.push!(df::DataFrame, obj::Var)` and update by passing `params(obj)` and `values(obj)`.  This corresponds better with, say, initializing a vector, then adding items with push!
- `params(obj)` / `values(obj)`: if you expect to return vectors, then i'd pluralize
- `tracedata(obj, y, b, args...)` makes a little more sense. (i.e. pass in an object as opposed to a DataType).  this way you can initialize with some initial batch if you want, as well as making it easier to have different weightings, etc.  The equivalent call would now be `tracedata(Var(), y, b)`
- `onlinefit(Distribution,y)`: sounds good... I assume that would return an object, so that successive calls to `update!(obj,y)` would continue to fit the same distribution?

**Comment by joshday** [comment]
The constructor/push! idea looks more correct.  

Ideally we'd avoid name conflicts with `Distributions.params`, and `Base.values`.  I vote for changing `values` to `state`.  `param` was mostly a small convenience for `Base.show()` methods, so maybe it's best to just drop it.

I like that idea for `tracedata`.

Yes, your assumption for `onlinefit` is correct.

Function names are then:
- `nobs(obj)`: number of observations used
- `state(obj)`: return the current estimate
- `tracedata(obj, y, b, args...)`: pass object, not DataType
- `onlinefit(Distribution, y)`: returns an object for calling `update!(obj, y)`

**Comment by tbreloff** [comment]
should I continue working on my forked version, or would you like me to clone yours and work in a separate branch?  both can work, but it would be more straightforward to clone.

**Comment by joshday** [comment]
Go ahead and clone it.

**Comment by tbreloff** [comment]
i tried to push up my branch, but permission was denied.  you may have to
add me as a collaborator?

**Comment by joshday** [comment]
You've been added.

**Comment by joshday** [comment]
I've started using a non-exported `state_names` function to make `Base.show` and `DataFrames.DataFrame` easier.

**Comment by tbreloff** [comment]
Ok all seems to work now.  I've merged in your latest master and so I'll continue to work in the "tom" branch.  You should check it out once in a while and see if there's anything there you want to merge into yours.  No pressure on staying up to date with mine... only if you want the changes.

**Comment by joshday** [comment]
Excellent!  I'd love to start using Weighting into my types (and add a weighting type for stochastic approximation methods).  

Feel free to pull changes into master.  I'm fairly new to the whole git/collaborative workflow, so what is the best way for us to both keep working?  Is it best to try to keep the other informed on what we're working on so we have less merging to deal with?

Also, out of curiosity, what will you be working on?  I'm excited to see what you add, as I feel like the quality of OnlineStats has already gone up with a few of your suggestions.

**Comment by tbreloff** [comment]
I'm excited to see where it goes as well. One method that can work well if you want... We can both do development in separate branches ("josh" and "tom") and wait to merge into master until its release-worthy. If one of us implements something the other wants, we can just fetch/merge directly from the other development branch. 

It also might be a good idea to open issues for whatever we're working on, which would be a good way to track what the other is working on.  

In the short term I plan to implement incremental PCA and FLS algos, but I'll probably also do general fixes and optimizations as I think they're useful. I could see using distribution fits and various other things you're working on, so I'll help out where appropriate. Thanks for letting me collaborate!

**Comment by tbreloff** [comment]
There's a big discussion going on now within the community about naming conventions, but normally you would call the function `statenames()` or `statesymbols()` or something like that (no underscore unless necessary).  I'm fine either way.  Also... does it make sense to you to include `:n` as one of the state vars?  Seems appropriate to me, and makes creating the dataframe and printing easier.

**Comment by joshday** [comment]
I like `statesymbols()`, and I'd rather use `:nobs` for clarity, just because `:n` is going to show up as a parameter for some distributions.

For complete clarity:  
- `statesymbols()` will return a vector of parameter names plus `:nobs`.
- `state()` will return an equal length vector of corresponding values

**Comment by tbreloff** [comment]
sounds good.  right now i'm working on complete implementations of Mean and Var which include show/DataFrame/push, weighting, and proper merging.  Once done, we can review together to see if this is the framework/interface we want to to apply everywhere else as well.

**Comment by joshday** [comment]
On second thought, all the `names()` methods return symbols.  I have no real preference, but maybe `statenames` is more Julian?

**Comment by tbreloff** [comment]
sure.  statenames is fine
