### ISSUE TITLE
Reactive framework

### ISSUE THREAD

**Issue by tbreloff** [joshday/OnlineStats.jl#32]
It would be cool to have some helper functions (or macros?) to set up a Reactive pipeline for `OnlineStat`s.  Here's a toy example of what it may do under the hood.  I set up 2 `OnlineStat`s: a `Diff` and a `Mean`, with the goal of reproducing the equivalent of `mean(diff(x))` when `x` is the full data vector.  `liftdiff` is of type `Reactive.Lift{OnlineStats.Diff{Float64}}`.  Everytime you `push!` to `input`, reactive will take care of calling the function you pass it and place the return value inside the `Lift` object.  Then you can chain the first `Lift` to another one that updates an `OnlineStats.Mean` object.  One call to `push!` on the `Reactive.Input` will trigger the necessary updates and store the return values.

```
julia> using OnlineStats, Reactive

julia> input = Input(0.0);

julia> d = Diff(); m = Mean();

julia> liftdiff = lift(x -> (update!(d, x); d), input);

julia> liftdiff
Online OnlineStats.Diff{Float64}
 *     diff:  0.000000

 *     last:  0.000000

 *     nobs:  1

julia> typeof(liftdiff)
Reactive.Lift{OnlineStats.Diff{Float64}}

julia> liftmean = lift(d -> (if nobs(d) > 1; update!(m, diff(d)); end; mean(m)), liftdiff);

julia> empty!(d); empty!(m);

julia> println(d); println(m)
OnlineStats.Diff{Float64}{diff=0.0 last=0.0 nobs=0}
OnlineStats.Mean{OnlineStats.EqualWeighting}{μ=0.0 nobs=0}

julia> push!(input, 5.0)   # this passes our first data point through the reactive pipeline we set up

julia> println(d); println(m)
OnlineStats.Diff{Float64}{diff=0.0 last=5.0 nobs=1}
OnlineStats.Mean{OnlineStats.EqualWeighting}{μ=0.0 nobs=0}

julia> push!(input, 8.0)

julia> println(d); println(m)
OnlineStats.Diff{Float64}{diff=3.0 last=8.0 nobs=2}
OnlineStats.Mean{OnlineStats.EqualWeighting}{μ=3.0 nobs=1}

julia> push!(input, 3.0)

julia> println(d); println(m)
OnlineStats.Diff{Float64}{diff=-5.0 last=3.0 nobs=3}
OnlineStats.Mean{OnlineStats.EqualWeighting}{μ=-1.0 nobs=2}

julia> @assert value(liftmean) == mean(diff([5.,8.,3.]))  # compare to vector version
```

**Comment by joshday** [comment]
:+1: This looks super useful.  How about overloading `lift`?  Your use case here actually looks hard to generalize since you're lifting a function of an OnlineStat.  Should there also be a method with a function argument so that the `Lift` parameter type isn't an OnlineStat?  Then `myliftobject.value` would be the actual value you're looking for.  I don't know, maybe it overcomplices things.

```julia
function Reactive.lift(o::OnlineStat, f::Function, input::Input)
    lift(x -> (update!(o, x); f(o)), input)
end

d = Diff(); m = Mean();
liftdiff = lift(d, diff, input)
liftmean = lift(m, mean, liftdiff)
x = rand(100)
for xi in x
   push!(input, xi)
end
liftmean.value # same as mean(diff(x))
```

One thing I'd love to see is an easy way to lift several models.  I think that would make your high level model builder idea pretty easy to implement.

```julia
m1 = LinReg(10)
m2 = Adagrad(10)
m3 = QuantRegMM(10)
onlinelift(myinput, m1, m2, m3)
```

**Comment by tbreloff** [comment]
I like this idea.  I started working through a macro implementation that would look something like:
```
@stream Float64 diff(d) mean(m)
```
where the macro would extract the OnlineStat objects and inject calls to `lift`, similar to how the `@lift` macro in reactive is built.  I think this might be a little over complicated for not enough benefit.  I'll work on a design that uses your concept.

**Comment by joshday** [comment]
Should this be a function instead of a macro?  Since you're essentially constructing two new `Lift` objects, don't you need to assign them a name?  I'm not very familiar with Reactive, so I might be missing something.

**Comment by tbreloff** [comment]
Functions can generally do anything you'd do with a macro, but sometimes you can make the syntax really nice as compared to a function, by generating boilerplate code or perhaps swapping out the insides of an expression.  In this case maybe you could type:
```
input, output = @stream Float64 diff(d) mean(m)
```
instead of:
```
input = Input(0.0)
liftdiff = lift(d, diff, input)
output = lift(m, mean, liftdiff)
```
I do think the first pass should probably be functions-only, though.  I stopped work on the macro.

**Comment by joshday** [comment]
Okay, cool.  The one-liner macro version does look much nicer.

**Comment by tbreloff** [comment]
After writing this I went back to the macro version, and I just pushed up a barely functional version... see the test, which looks like this:

```
input = Input(0.0)
d = Diff()
m = Mean()
l = osr.@stream diff(input |> d) |> m

for x in [5., 8., 3.]
  push!(input, x)
end
```

**Comment by joshday** [comment]
Nice, I like the use of the pipe operator for it.

**Comment by tbreloff** [comment]
I added some helper constructors to be able to pipe (x,y) tuples to a regression... performance is pretty awful, although it works.  I'm not sure if it may be better to bypass Reactive all together and just have a simple replacement that wraps an `OnlineStat` with a list of dependencies, calling the `update!` methods as needed.  Here's the comparison, showing a 30x slowdown:

```
  context("Regression") do
    n, p = 1_000_000, 5;
    x = randn(n, p);
    β = collect(1.:p);
    y = x * β + randn(n)*10;

    input = RegressionInput()
    reg = Adagrad(p)
    l = @stream input |> reg

    for i in 1:length(y)
      push!(input, (row(x,i), y[i]))
    end
    @fact nobs(reg) => n
    show(reg); println()

    @time update!(reg, x, y)
    @time for i in 1:length(y)
      push!(input, (row(x,i), y[i]))
    end
  end
```
results:
```
React
[Reactive.Input{Float64}] 3.0
OnlineStats.Diff{Float64}{diff=-5.0 last=3.0 nobs=3}
OnlineStats.Mean{OnlineStats.EqualWeighting}{μ=-0.6666666666666665 nobs=3}
Reactive.Signal[[Reactive.Lift{OnlineStats.Diff{Float64}}] OnlineStats.Diff{Float64}{diff=-5.0 last=3.0 nobs=3}]
([Reactive.Lift{OnlineStats.Diff{Float64}}] OnlineStats.Diff{Float64}{diff=-5.0 last=3.0 nobs=3},)
[Reactive.Lift{OnlineStats.Mean{OnlineStats.EqualWeighting}}] OnlineStats.Mean{OnlineStats.EqualWeighting}{μ=-0.6666666666666665 nobs=3}
     - Regression
Online OnlineStats.Adagrad{OnlineStats.IdentityLink,OnlineStats.SquareLoss,OnlineStats.NoReg}
 *        β:  [1.1482626684749564,1.9213156191207352,2.966510277944784,3.936391035353868,4.926980845154204]

 *     nobs:  1000000


 112.857 milliseconds (1000 k allocations: 46875 KB, 3.09% gc time)
   3.559 seconds      (24000 k allocations: 1297 MB, 5.16% gc time)
5 facts verified.
```

**Comment by tbreloff** [comment]
Continuing to brainstorm.  Although I think Reactive.jl will work, I don't think it'll be fast enough to actually use.  I'm thinking through either:
- Releasing/using an event propagation framework I developed that is currently closed source, and using that instead
- Making a very fancy macro to effectively re-write the code:

```
# some notes on possible syntax:
  # pipe operator "|>" defines an implicit call to: update_get!(rhs, lhs...) = (update!(rhs, lhs...); rhs)
  # pipe operator with AVec/tuple as rhs implies you call update_get! for each member of rhs
  # arrow operator "=>" defines currying: "lhs => f(_)" implies "f(lhs)", "(lhs1, lhs2) => f(_)" implies "(f(lhs1), f(lhs2))"
  # equal "=" tags that node with a symbol (instead of using a gensym)

# update_get!(o, args...) is the temporary name for doing: (update!(o, args...); o)

# assuming these rough definitions, trying to model an AR(p) of log 
# returns with some aggregate of 5 different regression models:
price = FloatInput()
d = Diff()
w = Window(p)
varx = Variances(p)
vary = Variance()
reg1 = Adagrad(p)
reg2 = LinReg(p)
...
reg5 = ???
swarm = Swarm([reg1, ... , reg5])

# the following block:
@testit begin
  diff(log(price) |> d) |> window
  sx = lags(window) |> varx => standardize(_)
  sy = future(window) |> vary => standardize(_)
  (sx, sy) |> (reg1, reg2, reg3, reg4, reg5) => (sy - predict(_, sx)) |> swarm
end

# should be roughly equivalent to calling this on each new data point:
function updateprice(price::Float64)
  update(d, log(price))
  update!(window, diff(d))
  sx = standardize(update_get!(varx, lags(window)))
  sy = standardize(update_get!(vary, future(window)))
  tmp1 = sy - predict(update_get!(reg1, sx, sy), sx)
  tmp2 = sy - predict(update_get!(reg2, sx, sy), sx)
  tmp3 = sy - predict(update_get!(reg3, sx, sy), sx)
  tmp4 = sy - predict(update_get!(reg4, sx, sy), sx)
  tmp5 = sy - predict(update_get!(reg5, sx, sy), sx)
  update!(swarm, (tmp1, tmp2, tmp3, tmp4, tmp5))
end
```

**Comment by tbreloff** [comment]
Lots of awesome changes!  Please fast-forward to my commit with:
```
git fetch
git merge --ff-only origin/tom
```

The `@stream` macro is pretty powerful now.  Something like the brainstorming above should be possible.  The following should mostly work right out of the box (assuming we had the `Window` stat implemented of course):

```
# We want to solve an AR(p) time series regression on normalized log differences of prices.
# In addition, we want to fit 5 separate models at the same time, and aggregate the results
# given the stream of prediction errors:
# assume d, window, varx, vary, reg{i}, and swarm are OnlineStats that have all been instantiated

f = @stream begin
  diff(log($1) |> d) |> window
  sx = lags(window) |> varx |> standardize(_)
  sy = future(window) |> vary |> standardize(_)
  (sx, sy) |> (reg1, reg2, reg3, reg4, reg5) |> (sy - predict(_, sx)) |> swarm
end

map(f, prices)
# all OnlineStats have been updated :)
```

Check out react.jl for the docs, and see react_test.jl for some examples in action!

**Comment by joshday** [comment]
Cool, I'll take a look.

**Comment by tbreloff** [comment]
I made some improvements to the `@stream` macro, mostly better internals which produce cleaner code.  You should, at this point, be able to put almost arbitrary code after the call to `@stream`, and use the pipe operator whenever you want to update an `OnlineStat` or do currying (replacing underscores with the streamed data).  Check out the doc string in react.jl, as well as look at the tests in react_test.jl, and you should get a pretty good idea of how it works.

When you have time, please try it out... it would be great to throw a bunch of workflows at it and make sure it can handle anything you throw at it.

**Comment by joshday** [comment]
Looks cool.  I'll have time to take a better look at it tomorrow.

**Comment by joshday** [comment]
I was able to play around with this a bit.  I haven't broken anything yet.  

I think in general I may not like the pipe operator.  I've never used it before in any language, but I find it hard to read.  Maybe I'm just not used to it.  I know a lot of people love it.

**Comment by tbreloff** [comment]
I agree that the pipe operator was not my first choice, but it's something
that doesn't really clash with other operators, plus it's already being
used for currying, which is kind of what we're doing here.  So I only chose
it for consistency with julia...

**Comment by joshday** [comment]
That's fair.  I think it's the right choice.
