### ISSUE TITLE
Generic types for SGD and variants (averaging, momentum, stochastic proximal gradient)

### ISSUE THREAD

**Issue by joshday** [joshday/OnlineStats.jl#33]
Implementing these things should be easy and also useful, just follow the work done with Adagrad.  

It took about a minute to add quantile regression to @tbreloff 's Adagrad framework, so I'm thinking this is the best approach.  These generic types would also unify a few things (`LogRegSGD`, `QuantRegSGD`, etc.).

- [x] SGD
- [x] Averaging (somewhat taken care of with work going on in react.jl)
- [x] Momentum
- [x] Stochastic Proximal Gradient Descent

**Comment by joshday** [comment]
@tbreloff. If you get a chance, I'd appreciate your thoughts on this.

I started taking a look at using EmpiricalRisks.jl to see if that would work for Adagrad/SGD.  I like the idea of having a standard interface across packages, but I think using it would be more difficulty than it's worth.

Instead I reimplemented the abstract Link/Loss type structure you had for Adagrad and replaced it with a single abstract type SGModel.  It's a little bit more verbose than your stuff (take a look at streamstats/stochasticgradientmodels.jl), but it made it easier to add support vector machines and poisson regression.  

SGD can now do:

-  L1Regression
-  L2Regression
-  LogisticRegression
-  PoissonRegression
-  QuantileRegression
-  SVMLike (perceptron and SVM)
-  HuberRegression

I think the "ugliest" part about this is the gradient function `∇f` now takes a few unused arguments (things that only get used by PoissonRegression or SVMLike).

```julia
function update!(o::SGD, x::AVecF, y::Float64)
    yhat = predict(o, x)
    ε = y - yhat

    λ = weight(o) * o.η
    @inbounds for j in 1:length(x)
        g = ∇f(o.model, ε, x[j], y, yhat) + ∇j(o.penalty, o.β, j)
        o.β[j] -= λ * g
    end

    o.n += 1
    nothing
end
```

Do you have any concerns with this implementation?  I'm not attached to the names of things, but I did change some to be more familiar to statisticians.  I'd be happy to change Adagrad to use this.  It should be trivial.

**Comment by tbreloff** [comment]
I really like the concept, and I don't immediately see any issues with it.  Looks clean.  If all tests out, I don't mind you updating Adagrad to conform.

As for the FactCheck change you made... I think the operator precedence of `=>` has changed recently, which prompted the change.  I guess we'll have to change a lot of tests to keep up.  Lets make sure we do that all at once and then fast forward to a common commit after it's done.

**Comment by joshday** [comment]
Crossing off averaging, which can already be done by `@stream` or

```julia
function f(x,y)
    update!(sgd_object, x, y)
    update!(means_object, coef(sgd_object))
end
```

Also crossing off stochastic proximal gradient descent for now.  It's main use would be for lasso penalty, which I will be trying out this weekend to see if it generates a sparse solution.
