### ISSUE TITLE
Lasso with sparse solution

### ISSUE THREAD

**Issue by joshday** [joshday/OnlineStats.jl#36]
L1Penalty() is currently functional only for SGD.  It also typically sets coefficients "close" to zero and doesn't create a sparse solution.  

Given the usefulness of the Lasso, this needs to be improved.

**Comment by tbreloff** [comment]
I never did get around to implementing the dual averaging algorithm (which
in theory is a good method for improving convexity for L1 penalty)... it's
still on my list somewhere.  I've been spending more time with OnlineAI.jl
lately.

**Comment by joshday** [comment]
Okay, cool.  I think I found a good way to do it within SGD/Adagrad framework.  I’m gonna try that out first.

**Comment by joshday** [comment]
Got a working version of RDA in streamstats/rda.jl in the josh branch.  I tried it for L2Regression and LogisticRegression.  It appears to work with NoPenalty, L2Penalty, and L1Penalty.  It makes me nervous that I have no intuition behind what the algorithm is doing, but it apparently works.  Needs tests.

**Comment by tbreloff** [comment]
Cool! I'll check it out.
