### ISSUE TITLE
Use Weighting for parametric density estimation

### ISSUE THREAD

**Issue by joshday** [joshday/OnlineStats.jl#4]
Distribution estimation should have optional Weighting.

**Comment by tbreloff** [comment]
I think it makes sense to pass through everything to add the weighting integration.  I can make a go at that, since it will help me to get familiar with everything in the repo

**Comment by joshday** [comment]
Agreed, it's just the first class of problems I'm adding it to.

**Comment by tbreloff** [comment]
I changed (and pushed) `DEFAULT_WEIGHTING` to a call to `default(Weighting)`.  It seemed cleaner.  You might want to pull in those changes before adding weighting to too many more types.

**Comment by joshday** [comment]
Okay, thanks.

**Comment by joshday** [comment]
Current distributions implemented now use `Weighting`:

- FitBernoulli
- FitBeta
- FitBinomial
- FitDirichlet
- FitExponential
- FitGamma
- FitMultinomial
- FitMvNormal
- FitNormal
