### ISSUE TITLE
Allow matrices row or column based

### ISSUE THREAD

**Issue by tbreloff** [joshday/OnlineStats.jl#40]
Need to think on this topic a little more... I'd like to be able to support passing in an X matrix either NxT or TxN, but without annoyance for the user, and without re-coding everything twice.

**Comment by joshday** [comment]
Could we do something like what you've done with Plots, and have two "backends", `row_based` and `column_based`? 

The convenience `update!` functions could be rewritten something like:
```julia
function update!{T<:Real}(o::OnlineStat, x::AMat{T})
    if backend() = row_based
        for i in 1:nrows(x)
            update!(o, row(x,i))
        end
    else
        for i in 1:ncols(x)
            update!(o, col(x,i))
        end
    end
end
```

At the same time, this could get very confusing.  In order for Mean() to be consistent with Means() for observations-in-columns, would Means() only accept a 1xn Matrix?

**Comment by Evizero** [comment]
:100: ! using columns for the observation is such an easy-to-achieve performance boost for big dataset.

One way to avoid doubling code would be to use some kind of TransposeArrayview

**Comment by joshday** [comment]
I have this in my branch.  Since more specific methods exist, this only gets called if the `column` keyword is specified.  You don't get the convenience constructors that call `update!` for you, but it's just one more line of code.  Can this be closed with a few `update!` methods similar to what's below?  We can maintain that observations are in rows unless the user specifies differently with `update!`.

```julia
function update!(o::OnlineStat, x::AMat y::AVec; column::Bool = true)
    for i in 1:length(y)
        update!(o, col(x, i), y[i])
    end
end
```
Example:
```julia
# y is Vector, x is Matrix with observations in columns
o = StochasticModel(size(x,1))
update!(o, x, y, column=true)
```

**Comment by tbreloff** [comment]
My hesitation is that there's a performance penalty with keyword arguments... I'm trying to work through a way to do it with parameters (which will involve a TransposeView or something similar).   I do think this will be a good first try, though.

**Comment by Evizero** [comment]
Thanks for working on this!

In general, I agree with Tom concerning KW arguments. However, if the function having the KW arguments is some root function that is only called to trigger the learning (in contrast to some inner function that is called every other iteration) then I think KW arguments should be fine.

As a sidenote: Did you leave some code out in your example? the `column` parameter is never used in your code snipped.

**Comment by joshday** [comment]
Maybe it wasn't clear what I was doing.  The gist of my solution was having the following two methods.  It's not possible to call the second method without the keyword.  The loop is doing all the work, using ArrayViews to pass in the rows or columns of `x`.  I think my example is correct.

```julia
function update!(o::OnlineStat, x::AbstractMatrix{Float64}, y::AbstractVector{Float64})
    for i in 1:length(y)
        update!(o, rowvec_view(x, i), y[i])
    end
end

function update!(o::OnlineStat, x, y; column::Bool = true)
    for i in 1:length(y)
        update!(o, view(x, :, i), y[i])
    end
end
```

```julia
# observations in rows
o = StochasticModel(size(x, 2))
update!(o, x, y)

# observations in columns
o = StochasticModel(size(x, 1))
update!(o, x, y, column=true)
```

Things get trickier when updating mini batches, so I don't think this is the best solution.  Some TransposeView would be great.

**Comment by tbreloff** [comment]
Oh my mistake... this won't work as dispatch can't tell the difference
between them.  If you have 2 different functions, they should probably have
2 different names.  Otherwise a dispatch friendly approach should be used
(TransposeView, or similar)

**Comment by joshday** [comment]
I think this could be handled with an AbstractSeries subtype.  I'll try it when I get the chance.  See https://github.com/joshday/OnlineStats.jl/pull/74

**Comment by Evizero** [comment]
maybe not the right thing for this particular package, but for the sake of completeness:

Our observation dimension code is in LearnBase now https://github.com/JuliaML/LearnBase.jl/blob/master/src/LearnBase.jl#L202-L232. This is what we use in the JuliaML packages currently to allow specifying what array dimension enumerates the observations.

from an package-user perspective it allows for code that looks like:

```
# as convenient keyword
f(X, obsdim=1)
f(X, obsdim=2)
f(X, obsdim=:last)
f(X, obsdim=:first)

# as typestable positional
f(X, ObsDim.First())
f(X, ObsDim.Last())
f(X, ObsDim.Constant{2}())
```

**Comment by joshday** [comment]
I forgot that stuff lived in LearnBase!  That's great.  I think that is the way to go and can probably be handled by some extra `fit!` methods then.

**Comment by Evizero** [comment]
The general gist looks like this

```julia
# keyword interface just maps to positional (default_obsdim(::AbstractArray) defaults to ObsDim.Last())
function foo(X, arg1, arg2; obsdim = LearnBase.default_obsdim(X))
    foo(X, arg1, arg2, LearnBase.obs_dim(obsdim))
end

# Optional: map ObsDim.Last to the concrete ObsDim.Constant{N} to avoid duplicated code
function foo{T,N}(X::AbstractArray{T,N}, arg1, arg2, ::ObsDim.Last)
    foo(X, arg1, arg2, ObsDim.Constant{N}())
end

function foo(X, arg1, arg2, ::ObsDim.Constant{1})
    # ... actual code for when each row is an observation ...
end

function foo(X, arg1, arg2, ::ObsDim.Constant{2})
    # ... actual code for when each column is an observation ...
end

# ... more functions if higher order arrays are also relevant ...
```

**Comment by joshday** [comment]
I added an some`fit!` methods to handle this:

https://github.com/joshday/OnlineStats.jl/blob/master/src/series.jl#L156-L173

By convention in JuliaML, do functions have both the keyword and positional argument versions?

**Comment by Evizero** [comment]
This comment seems wrong: https://github.com/joshday/OnlineStats.jl/blob/master/src/series.jl#L155, because it is `obsdim=2` in that case.

> By convention in JuliaML, do functions have both the keyword and positional argument versions?

No. For example in LossFunctions we don't have the keyword one. The reason is that as computational kernels it would miss the point to have kw argument overhead.

However, it does feel cleaner to have at all the options supported. For example right now it looks like I'd get a `MethodError` when calling `fit(s, y, ObsDim.First())`.

-----

You know, just to put the option out there (and obviously to brag with its real use-case applicability), once [`MLDataPattern.jl`](https://github.com/JuliaML/MLDataPattern.jl) is registered, the code "could" be reduced to:

```julia
# Any order array (vector, matrix, ...); any obsdim
function fit!(s::Series{1}, y::AbstractArray, obsdim::ObsDimension=LearnBase.default_obsdim(y))
    for i in 1:nobs(y, obsdim)
        fit!(s, datasubset(y, i, obsdim)) # datasubset creates a SubArray for Arrays
    end
    s
end
```

or

```julia
# Any order array (vector, matrix, ...); any obsdim
function fit!(s::Series{1}, y::AbstractArray, obsdim::ObsDimension=LearnBase.default_obsdim(y))
    for y_i in obsview(y, obsdim)
        fit!(s, y_i) # each y_i is a SubArray for Arrays
    end
    s
end
```

That said, the way you implemented it looks good as it is.

**Comment by joshday** [comment]
You're right about my comment.  I was confused about how ObsDim worked at first.

I really like your second example!  That's exactly what I'm looking for...At first I didn't read your comment carefully and I started working on my own data iterators.  That looks fantastic.

**Comment by joshday** [comment]
This has been fixed for a few months...just forgot to close it.  I also added some aliases for ObsDim.

```julia
julia> s = Series(CovMatrix(2))
▦ Series{1,CovMatrix,EqualWeight}
┣━━ EqualWeight(nobs = 0)
┗━━ Tracking
    ┗━━ CovMatrix([0.0 0.0; 0.0 0.0])

julia> fit!(s, randn(100,2), Rows())
▦ Series{1,CovMatrix,EqualWeight}
┣━━ EqualWeight(nobs = 100)
┗━━ Tracking
    ┗━━ CovMatrix([1.39497 -0.0716307; -0.0716307 0.969718])

julia> fit!(s, randn(2, 100), Cols())
▦ Series{1,CovMatrix,EqualWeight}
┣━━ EqualWeight(nobs = 200)
┗━━ Tracking
    ┗━━ CovMatrix([1.2151 0.0241617; 0.0241617 0.973139])
```
