### ISSUE TITLE
Better update! 

### ISSUE THREAD

**Issue by joshday** [joshday/OnlineStats.jl#41]
`update!` should be able to do:

- singleton and minibatch updates
- support callbacks 

`onlinefit!` will be removed.  `updatebatch!` will no longer be exported.  Callbacks aren't incorporated yet.  Here's what I got so far:

```julia
# b is batch size
function update!(o::OnlineStat, y::Union{AVec, AMat}, b::Integer = 1)
    b = Int(b)
    n = size(y, 1)
    @assert 0 < b <= n "batch size must be positive and less than data size"
    if b == 1
        for i in 1:n
            update!(o, row(y, i))
        end
    else
        i = 1
        while i <= n
            rng = i:min(i + b - 1, n)
            updatebatch!(o, rows(y, rng))
            i += b
        end
    end
end

# If an OnlineStat doesn't have an updatebatch method, just use update
updatebatch!(o::OnlineStat, data...) = update!(o, data...)
```

**Comment by tbreloff** [comment]
:+1:  This is definitely an improvement.  We should do some benchmarking at some point to see whether the combined logic slows down inner loops if we're always just passing one row at a time.

**Comment by Evizero** [comment]
I love that you want to include callbacks!

**Comment by joshday** [comment]
Update methods are in decent shape now.  What are the main use cases you guys are thinking of for callbacks?
