### ISSUE TITLE
DataStreams

### ISSUE THREAD

**Issue by tbreloff** [joshday/OnlineStats.jl#43]
Implement interface of:  https://github.com/JuliaDB/DataStreams.jl

**Comment by joshday** [comment]
Now that OnlineStats relies on iteration instead of assuming data is in an AbstractVector, things that satisfy the Tables.jl interface work out of the box:

```julia
julia> using OnlineStats, IndexedTables

julia> t = table((x=1:100, y=rand(100)));

julia> fit!(2Mean(), t)
Group
  ├── Mean: n=100 | value=50.5
  └── Mean: n=100 | value=0.526997
```
