### ISSUE TITLE
Move away from ArrayViews

### ISSUE THREAD

**Issue by tbreloff** [joshday/OnlineStats.jl#44]
Can replace with `slice` which produces a `SubArray`.  ArrayViews is apparently obsolete at this point.

**Comment by joshday** [comment]
I saw some of that discussion in julia-users, so I tried making this change:

```julia
row(x::AMat, i::Integer) = slice(x, i, :)
```

It was slightly slower than `rowvec_view` and added ~60MB of allocations for updating a stochastic model using a million by 5 design matrix.  I'll try some different data sizes to see how they compare.

**Comment by joshday** [comment]
Using a million by 50 design matrix,  

- `rowvec_view`:  
  - `0.686121 seconds (2.02 M allocations: 565.355 MB, 24.64% gc time)`
- `slice`:
  - `0.899129 seconds (6.02 M allocations: 656.899 MB, 29.32% gc time)`

Is there a `rowvec_view` equivalent in Base I should be trying instead?

**Comment by tbreloff** [comment]
Not sure... can you post the benchmark code you used?

**Comment by joshday** [comment]
I was using a new type, `OnlineGLM`.  The same thing is seen with `SGModel`, which I've renamed `StochasticModel`.

```julia
n, p = 1_000_000, 50
x = randn(n, p)
β = vcat(1.:p) / p

# poisson regression
y = Float64[rand(Distributions.Poisson(exp(xb))) for xb in x*β]

# @time o = OnlineStats.OnlineGLM(x, y, OnlineStats.LearningRate(r=.8), family = Distributions.Poisson())
@time o2 = OnlineStats.StochasticModel(x,y,model = OnlineStats.PoissonRegression(), algorithm = OnlineStats.SGD(r=.7), intercept = false)
```

**Comment by joshday** [comment]
Since ArrayViews is still faster, I'm going to close this for now.  With the changes to arrays in 0.5, I'll revisit this when we get close to a 0.5 release.

**Comment by joshday** [comment]
I just discovered something in favor of SubArrays;  SubArrays work with SparseMatrixCSC and ArrayViews does not.  I'd like to look into the performance differences some more.  Is the minor performance hit worth supporting sparse matrices?

**Comment by joshday** [comment]
I've switched stuff from ArrayViews to SubArrays.
