### ISSUE TITLE
Iterative GAMs?

### ISSUE THREAD

**Issue by datnamer** [joshday/OnlineStats.jl#45]
http://onlinelibrary.wiley.com/doi/10.1111/rssc.12068/abstract

**Comment by joshday** [comment]
I haven't had the time to look into this, but I'm interested in the idea.

**Comment by datnamer** [comment]
Great! What do you think of tmle :)?

**Comment by joshday** [comment]
I don't think I know enough about it to say anything intelligent yet.

**Comment by joshday** [comment]
I think this is outside of the scope of OnlineStats and would do better as an external package which imports OnlineStats.
