### ISSUE TITLE
TMLE For confidence intervals etc

### ISSUE THREAD

**Issue by datnamer** [joshday/OnlineStats.jl#46]
Would be really cool to have online (or even batch TMLE) either in the package or interfacing with it. 

Intro: http://blog.revolutionanalytics.com/2015/03/ 
http://www.bu.edu/cphs/files/2013/01/Mark-van-der-Laan-Targeted-Learning-with-Big-Data.pdf
Online targeted learning: http://biostats.bepress.com/ucbbiostat/paper330/
Julia implementation of batch TMLE: https://lendle.github.io/TargetedLearning.jl/

**Comment by joshday** [comment]
This is something I don't think I'll ever get to.  PRs without adding dependencies are welcome, or this could be done in a separate package through OnlineStatsBase.
