### ISSUE TITLE
Start using Logging.jl?

### ISSUE THREAD

**Issue by joshday** [joshday/OnlineStats.jl#47]
@tbreloff Any arguments for or against switching to use https://github.com/kmsquire/Logging.jl?  Logging in OnlineStats is undocumented/untested.  It'd be nice to shift that responsibility to a maintained package.

**Comment by tbreloff** [comment]
I just took a look at the code... I think it should be ok to switch if you want.

**Comment by joshday** [comment]
After trying Logging.jl, I decided against it.  I don't like that it overwrites Base.info and Base.warn by importing.

**Comment by Evizero** [comment]
That does seem weird. It might be worth reporting your thoughts on that there. Maybe the author is open to change that.

**Comment by joshday** [comment]
Just opened an issue there.
