### ISSUE TITLE
IPCA

### ISSUE THREAD

**Issue by tbreloff** [joshday/OnlineStats.jl#5]
Update PCA loading matrix incrementally

**Comment by tbreloff** [comment]
Considering using algo # 2 from:
http://www.cs.yale.edu/homes/el327/papers/opca.pdf

**Comment by tbreloff** [comment]
Also want to review other papers to see if there's a better alternative method:
https://www.cs.nyu.edu/~roweis/papers/empca.pdf
http://arxiv.org/pdf/0712.4273v3.pdf

**Comment by tbreloff** [comment]
Hey Josh... Do you think you could help me come up with a couple tests for OnlinePCA?   I have an outline but could use another brain.

**Comment by joshday** [comment]
Sure thing.  I'd like to run through the "Candid..." paper first, so I'll try to think of some tests as I go through it.

**Comment by tbreloff** [comment]
I saw that you added AnalyticalPCA... it's a good idea to compare/test.  Thanks.

**Comment by joshday** [comment]
I'd still like to help write some actual tests.  Last week was busy for me.  I should be able to find time this week.

**Comment by joshday** [comment]
Just noting here that I've added a relatively simple method for CovarianceMatrix that will give return a specified number of components.  This is more useful than AnalyticalPCA since you can choose the number of components to look at.

```julia
function pca(o::CovarianceMatrix, nev::Int = length(o.B), corr::Bool = true; keyargs...)
    if nev == length(o.B)
        if corr
            eig(Symmetric(cor(o)))
        else
            eig(Symmetric(cov(o)))
        end
    else
        if corr
            eigs(cor(o), nev = nev, which = :LR, keyargs...)
        else
            eigs(cor(o), nev = nev, which = :LR, keyargs...)
        end
    end
end
```
