### ISSUE TITLE
Inf in Variance value

### ISSUE THREAD

**Issue by tbreloff** [joshday/OnlineStats.jl#51]
I don't like the behavior when trying to get a running vector of the variance of a series:

```
using OnlineStats
v = Variance(ExponentialWeight(10))
x = sin(1:100) .* rand(100)
xvar = Float64[(fit!(v, xi); std(v)) for xi in x]
```

gives the error:

```
LoadError: DomainError:
while loading In[4], in expression starting on line 4

 in std at /home/tom/.julia/v0.4/OnlineStats/src/summary.jl:69
 in anonymous at no file
```

The value of v is -Inf, but that doesn't feel like what we want.  Even if it's "technically correct", it makes working with a `Variance` really tricky.

```
v
Out[5]:
▌ Variance 
  ▶     value: -Inf
  ▶      nobs: 1
```

**Comment by tbreloff** [comment]
Actually is there a bug here?  https://github.com/joshday/OnlineStats.jl/blob/master/src/summary.jl#L65

**Comment by tbreloff** [comment]
It works ok for EqualWeight but ExponentialWeight is completely wrong.

**Comment by tbreloff** [comment]
Here's a simple example:

```
julia> x = randn(100);

julia> var(x)
1.162888972180564

julia> v = Variance()
▌ Variance 
  ▶     value: -0.0
  ▶      nobs: 0

julia> fit!(v, x); v
▌ Variance 
  ▶     value: 1.1628889721805642
  ▶      nobs: 100


julia> v = Variance(ExponentialWeight(10))
▌ Variance 
  ▶     value: -0.0
  ▶      nobs: 0


julia> fit!(v, x); v
▌ Variance 
  ▶     value: -1.976802951354775e189
  ▶      nobs: 100
```

**Comment by joshday** [comment]
That is quite the bug!  I'll take a look.

**Comment by joshday** [comment]
`var(o::Variance)` now behaves a bit better:
```julia
julia> xvar = Float64[(fit!(v, xi); std(v)) for xi in x]
100-element Array{Float64,1}:
 0.0
 0.03677
 0.265324
 0.537096
...
```

In my rewrite, I apparently missed a method for `ExponentialWeight(minstep::Integer)`, so your example was using a nonsensical weight of 10 for each update.  This has been fixed.
```julia
julia> x = randn(100);

julia> v = Variance(ExponentialWeight(20));

julia> fit!(v, x); v
▌ Variance
  ▶     value: 0.9294099372585689
  ▶      nobs: 100
```

The line you pointed out comes straight from Knuth's Art of Computer Programming, but I'm not sure it's correct for non-EqualWeight updates.  I'll leave this open while I look into it.

**Comment by joshday** [comment]
http://www-uxsup.csx.cam.ac.uk/~fanf2/hermes/doc/antiforgery/stats.pdf confirms the update is the same for ExponentialWeight (see equation 142, equation 143 has a typo).

**Comment by tbreloff** [comment]
Great thanks for following up!
