### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by joshday** [joshday/OnlineStats.jl#54]
I started working on generating documentation from the OnlineStats doc strings. 

This:
https://github.com/joshday/OnlineStats.jl/blob/dev/doc/knit.jl

generates this:
https://github.com/joshday/OnlineStats.jl/blob/dev/doc/api.md

There's clearly a lot of stuff that needs to be documented better.

**Comment by Evizero** [comment]
That pretty cool!

**Comment by tbreloff** [comment]
:+1:

**Comment by joshday** [comment]
Going back to mkdocs.  Things in OnlineStats are much less of a moving target compared to last time I was using it.   https://joshday.github.io/OnlineStats.jl/

**Comment by tbreloff** [comment]
Fyi I've used mkdocs for Plots and it works well... Feel free to copy/use
anything from there (PlotDocs.jl)

**Comment by joshday** [comment]
Very cool.  I didn't know about PlotDocs.  I'll take a look.

**Comment by joshday** [comment]
Closing now that I'm up and running with mkdocs.
