### ISSUE TITLE
Base.merge methods

### ISSUE THREAD

**Issue by joshday** [joshday/OnlineStats.jl#61]
Mentioned at https://github.com/johnmyleswhite/StreamStats.jl/issues/24.

These got left behind during a rewrite.  They need to be added back in.

**Comment by mauro3** [comment]
Yes, I'd love to have this for my work too.

(And thanks for the great package!)

**Comment by joshday** [comment]
Thanks for the kind words!  My summer work just ended, so I'll be able to spend more time on OnlineStats.  Let me know if you have a preference/recommendation with where I start.

**Comment by mauro3** [comment]
Oh, I see, its in master: https://github.com/joshday/OnlineStats.jl/blob/master/src/OnlineStats.jl#L336
Although there it should read `o1`.

I'd also need, eventually, merging of `Moments`, `Extrema`, and `Quantiles`.

(Off-topic: can the median be calculated online too?)

**Comment by joshday** [comment]
Good catch...that's clearly untested.  Yes, median is the .5 quantile.  

As a heads up, the dev branch is 0.5-only.  I'll be working there to start with.

**Comment by mauro3** [comment]
Haha, I just outed myself as a complete stats noob...

**Comment by mauro3** [comment]
Yay!: https://github.com/joshday/OnlineStats.jl/blame/e61290e460a7615af2beb6904fb3972fe5c9185d/src/summary.jl#L145 , although the function is missing a return value.

Also, this https://github.com/joshday/OnlineStats.jl/blob/e61290e460a7615af2beb6904fb3972fe5c9185d/src/OnlineStats.jl#L330 should probably also have the default `method::Symbol = :append`.  Thanks!

**Comment by tbreloff** [comment]
I had a chuckle when I saw the bottom part of this from the link:

![ostats](https://cloud.githubusercontent.com/assets/933338/18053861/71f71336-6dcf-11e6-998a-3cdcd46f42c6.png)

You're a crazy guy @joshday... breaking everything with your whitespace!

**Comment by joshday** [comment]
Thanks for the comments, @mauro3!  I made a few changes/added a method to provide your own weight.

**Comment by mauro3** [comment]
This can be closed, right?

**Comment by joshday** [comment]
Yes, I think so.
