### ISSUE TITLE
Support 0.5

### ISSUE THREAD

**Issue by joshday** [joshday/OnlineStats.jl#62]
dev branch is now 0.5 only and I think I've fixed all deprecation warnings.  Before any 0.5-only code makes its way to master, I'd like to publish one more release.

**Comment by colbec** [comment]
@joshday Not sure if relevant here, but in Julia 0.6 latest version I have problems in `Pkg.test("OnlineStats")`. 
Functions `sub` and `slice` are deprecated in favour of `view`, but perhaps more important the tests error out on function `smooth!()` which appears to be unknown. Smooth was previously mentioned in https://github.com/joshday/OnlineStats.jl/issues/23.

**Comment by joshday** [comment]
I've still only updated the dev branch for 0.5.  You can try `Pkg.checkout("OnlineStats", "dev")`

**Comment by colbec** [comment]
Thanks, `Pkg.checkout("OnlineStats", "dev")` and rebuild passes Pkg.test() on Version 0.6.0-dev.446 just fine.

**Comment by ViralBShah** [comment]
I just tried the latest tagged release and see one warning:

```
julia> using OnlineStats

WARNING: deprecated syntax "Base.(:-)".
Use "Base.:-" instead.
```

**Comment by joshday** [comment]
I was planning on getting one more 0.4-supported release out, but I don't think I'll have time.  I'll get a new version tagged ASAP.

**Comment by joshday** [comment]
0.5-only release is now in METADATA.
