### ISSUE TITLE
Make OnlineStat subtypes immutable & isbits?

### ISSUE THREAD

**Issue by mauro3** [joshday/OnlineStats.jl#63]
The current strategy when having many simultaneous streams is to make a new type (`Means` and `Variances` so far) and keep the stats of all streams in there.  Have you tried to instead make the `OnlineStat` subtypes immutable and isbits, then having an array of them should be efficient?  It would waste the memory for the common fields, such as `nobs`, but it would make the multi-stream work without extra effort on your part.

**Comment by tbreloff** [comment]
Hi @mauro3.  I don't quite understand how you would update the fields of an immutable.  You'd have to construct a new object, and set the array position to point to the new object.  This changes the representation and implementation.

Can we use https://github.com/simonster/StructsOfArrays.jl instead?

**Comment by mauro3** [comment]
Yes, I guess the `fit!` would need to change to `fit`.  (But that would still be the case for StructsOfArrays, no?)

It would look like:
```
ms = [Moments() for i=1:10^5]
...
for i in eachindex(result)
  ms[i] = fit(ms[i], result[i])
end
...
```
So OnlineStats wouldn't need to worry about arrays of `Moments`, etc..  And the user would just do normal looping.

**Comment by joshday** [comment]
As a possible solution to get rid of Means/Variances, I've had a few attempts at creating a way for OnlineStats to share the same Weight object, but I haven't found a good solution yet.

I imagine this is something that would be difficult to get working for more complicated types?
```julia
type StatLearn{
        A <: Algorithm,
        M <: Model,
        P <: Penalty,
        W <: StochasticWeight
    } <: OnlineStat{XYInput}

    β0::Float64     # intercepts
    β::VecF         # coefficients
    intercept::Bool # should β0 be estimated?
    η::Float64      # constant part of learning rate

    # Storage
    H0::Float64
    G0::Float64
    H::VecF
    G::VecF

    algorithm::A    # determines how updates work
    model::M        # model definition
    penalty::P      # type of penalty
    weight::W       # Weight, may not get used, depending on algorithm
end
```

**Comment by mauro3** [comment]
It would only make sense with `isbits` types and for those, all the fields need to be isbits too.  Some, like the `VecF`, could be replaced with https://github.com/SimonDanisch/FixedSizeArrays.jl. (Aside, I just checked and to my surprise function types are isbits: `isbits(sin)==true`.)

**Comment by joshday** [comment]
I think the ability to use different Weight types is one of the unique features of OnlineStats, and this would remove that as far as I understand.  I also want the API to be consistent, so I probably won't be working on this.  I would consider adding something like `ImMean <: ImmutableOnlineStat` separate from `Mean <: OnlineStat`, but would need some proof of performance gains first.

**Comment by mauro3** [comment]
No, I don't think so.  The weights could be immutable & isbits, at least the ones defined in weight.jl.

Anyway, fair enough.  I just thought I'd post it here for a discussion: thanks!  Feel free to close (or leave open).

**Comment by joshday** [comment]
I'll leave it open for now in case someone comes across the issue and wants to give it a try.

**Comment by joshday** [comment]
The current rewrite started with me exploring immutable types and I was unable to get noticeably better performance, so I'm closing this for now.

**Comment by mauro3** [comment]
Looks like this was solved with https://github.com/joshday/OnlineStats.jl/releases/tag/v0.8.0
