### ISSUE TITLE
support complex?

### ISSUE THREAD

**Issue by nbecker** [joshday/OnlineStats.jl#64]
At least 2nd order stats for complex data types are useful

**Comment by joshday** [comment]
I've thought about supporting other Number types.  It would require a bit of an overhaul.  What's the use case for complex numbers?

**Comment by nbecker** [comment]
Used very commonly in communications - signals are usually represented as complex vectors

**Comment by nbecker** [comment]
I made a simple outline of a 2nd order complex accumulator here:
https://gist.github.com/nbecker/58f79e449400159e4762f6c8eedd9f65

I'm a julia newb - I really would rather have:
type var{T} where T is Complex{Float64}, for example, but I can't figure out how to get the element type from the Complex{Float64} type, which was the attempted code that's commented out.  Is this a hole in Julia's type system?  In c++ this is done with some template metaprogramming.

**Comment by joshday** [comment]
This is a question for julia-users, but this may get you started:

```julia
julia> a = 1 + 1im
1 + 1im

julia> fieldnames(a)
2-element Array{Symbol,1}:
 :re
 :im

julia> typeof(a.re)
Int64
```

Just to clarify, I'm not able to use your gist as a template for adding this to OnlineStats.  Supporting Complex would require a rewrite of the Weight types as well as updating a lot of abstract methods.

**Comment by nbecker** [comment]
Updated gist with a version that handles both scalar and complex

**Comment by joshday** [comment]
This was actually not bad to implement.  You can now (on OnlineStatsBase master) wrap an OnlineStat in `CStat` to track the real and imaginary parts separately.

```julia
using OnlineStats

julia> y = randn(100) + randn(100)im;

julia> Series(y, CStat(Mean()))
▦ Series{0,Tuple{CStat{Mean}},EqualWeight}
┣━━ EqualWeight(nobs = 100)
┗━━━┓
    ┗━━ CStat: re = Mean(-0.157636), im = Mean(-0.0383956)
```

**Comment by nbecker** [comment]
Thanks for helping with this - so stats are simply computed separately on real and imag parts?

For work in communications, for 2nd order stats, the variance is defined

var = E[x**2] - E[x]**2.

I don't you can get this from the stat computed on real and imag separately?

**Comment by joshday** [comment]
Based on https://en.wikipedia.org/wiki/Complex_random_variable#Variance, this would return the variance:

```julia
o = CStat(Variance())
Series(data, o)
sum(value(o))
```

**Comment by nbecker** [comment]
Sorry, I should have checked what I wrote more carefully - the variance given by the above ref is the desired definition.
