### ISSUE TITLE
Documentation example error

### ISSUE THREAD

**Issue by ViralBShah** [joshday/OnlineStats.jl#65]
```
julia> maprows(100, x, y) do xi, yi
           fit!(o, xi, yi)
           info("You have fit $(nobs(o)) observations")
       end
ERROR: UndefVarError: maprows not defined
```

**Comment by joshday** [comment]
As far as I know, mkdocs doesn't support multiple versions of docs, so the docs are slightly out of sync with release.  Try `map_rows` (I changed it to be more consistent with `mapslices`) or checkout the dev branch.  Now that 0.5 is out, I'll push a new release this week.

**Comment by joshday** [comment]
New release is in METADATA and synced up with docs.
