### ISSUE TITLE
Move StatLearn, etc. out of OnlineStats

### ISSUE THREAD

**Issue by joshday** [joshday/OnlineStats.jl#67]
More of an announcement than an issue, but I'm moving statistical modeling types (`<: OnlineStat{XYInput}`) into its own package https://github.com/joshday/OnlineStatsModels.jl.

A couple reasons for this:
- `OnlineStatsModels` is `OnlineStats + Losses + Penalties + (assume a linear transformation)`.  The main thing I want to cover is generalized linear models, but also add SVMs, quantile regression, etc.  It's essentially a smaller-scope StochasticOptimization, so it may become obsolete or should depend on StochasticOptimization.
- The interface for OnlineStats has been stable for a while, apart from modeling types.  This gives me a little more freedom to break things and experiment with algorithms for my research.

**Comment by tbreloff** [comment]
> so it may become obsolete or should depend on StochasticOptimization.

I'd really like to merge OnlineStats and JuliaML somehow... they're so similar in a lot of ways.  I have no problems with experiments, as long as the end goal is collaboration! :+1:
