### ISSUE TITLE
Mixed models

### ISSUE THREAD

**Issue by skanskan** [joshday/OnlineStats.jl#78]
Please add the option to fit models with random effects as MixedModels.jl does but for large datasets not fitting in memory.

**Comment by joshday** [comment]
Do you have a link to a paper for an algorithm which does this?

**Comment by skanskan** [comment]
https://www.jstatsoft.org/article/view/v067i01/v67i01.pdf

I know very little about its details.

In Julia there is the MixedModels.jl package.
In R there is the lme4 and an older nlme packages.
All work well but cannot deal with large datasets.

**Comment by joshday** [comment]
Without something actionable here, I'm gonna go ahead and close the issue.  If you find a method for doing this, post a link and I'll be happy to add it!
