### ISSUE TITLE
OnlineFLS

### ISSUE THREAD

**Issue by tbreloff** [joshday/OnlineStats.jl#8]
modeled on http://www2.econ.iastate.edu/tesfatsi/FLSTemporalDataMining.GMontana2009.pdf

- [x] Write draft
- [x] Tests

**Comment by tbreloff** [comment]
Hey Josh... Any interest in reviewing what I've done in FLS?  I could certainly use your eye to find any mistakes/inconsistencies, etc with the math.

**Comment by joshday** [comment]
Sure thing, I'll take a look.

**Comment by joshday** [comment]
I don't understand what every piece is, but `update!()` looks like a faithful reproduction of their algorithm.  Math and everything else looks good.

**Comment by joshday** [comment]
Since standardizing variables is going to be common, maybe we need a `XYMeanVar` type.

**Comment by tbreloff** [comment]
Thanks... glad to hear the math looks good.  Yes some generic normalization types/methods would be great to add.  I'll think on what design might be best.
