### ISSUE TITLE
Checks on distribution parameters?

### ISSUE THREAD

**Issue by ValdarT** [joshday/OnlineStats.jl#83]
There are currently no checks that the distribution parameters are valid. For example:
```
using OnlineStats, Distributions
s = Series(FitGamma())
fit!(s, 23)
fit!(s, 23)
Gamma(value(s)...)

ERROR: ArgumentError: Gamma: the condition α > zero(α) && θ > zero(θ) is not satisfied.
```
This happens because the variance is 0, of course.

At first sight, it seems that there should be checks in OnlineStats whether the distribution parameters are valid. At the same time, the next value could be 24 which would give a defined distribution. So it would be undesirable if the fitting errors out before getting there. Which got me thinking that it might be better to handle the 0 variance in some way (like adding a very small value) so that the distribution fitting would still work even with constant values.

I know it is really a corner case but what are your thoughts on this?

**Comment by joshday** [comment]
You run into the same problem if you fit it offline, so I don't think it's worth worrying about.  

```
julia> using Distributions

julia> fit(Gamma, [23, 23])
ERROR: ArgumentError: Gamma: the condition α > zero(α) && θ > zero(θ) is not satisfied.
```

Also, `Gamma(value(s)...)` already does the check, so having the same check for `value(s)` may be a bit redundant.

**Comment by ValdarT** [comment]
Ok, sure. Closing.
