### ISSUE TITLE
Simple example of how to fit logistic regression

### ISSUE THREAD

**Issue by xiaodaigh** [joshday/OnlineStats.jl#89]
Can you please provide a simple example of how to fit logistic regression or any type of GLM using this package? I am very interested but this is too short and hard doesn't really give an idea of how to use it. http://joshday.github.io/OnlineStats.jl/latest/pages/api.html#OnlineStats.StatLearn

**Comment by joshday** [comment]
Looks like the formatting in the example got messed up.  I'll clean it up.

```julia
using LossFunctions, PenaltyFunctions 

# just generating some fake data
x = randn(100_000, 10) 
y = x * linspace(-1, 1, 10) + randn(100_000) 

o = StatLearn(10, L2DistLoss(), L1Penalty(), fill(.1, 10), SGD()) 
s = Series(o) 
fit!(s, x, y) 

coef(o) 
predict(o, x)
```

**Comment by skanskan** [comment]
> using LossFunctions, PenaltyFunctions

Hello

When I try to replicate your example I need to replace linspace with range but I get this error

> ERROR: MethodError: no method matching fit!(::Series{Union{Tuple, AbstractArray{T,1} where T, NamedTuple},Tuple{StatLearn{SGD,LPDistLoss{2},L1Penalty,LearningRate}}}, ::Array{Float64,2}, ::Array{Float64,1})

**Comment by joshday** [comment]
Syntax has changed slightly: `fit!(o, (x,y))`

**Comment by joshday** [comment]
(And you don't need to put the `StatLearn` object inside a `Series` first)

**Comment by skanskan** [comment]
Could you please post other example showing how is the syntax if I want to fit a linear regression, or a logistic regression or a mixed-effects regression?

**Comment by xiaodaigh** [comment]
For a more complete example

```julia
using LossFunctions, PenaltyFunctions 

# just generating some fake data
x = randn(100_000, 10) 
y = x * range(-1, stop=1, length=10) + randn(100_000) 

o = StatLearn(10, L2DistLoss(), L1Penalty(), fill(.1, 10), SGD()) 
fit!(s, zip(eachrow(x), y)) 

coef(o) 
predict(o, x)
```
