### ISSUE TITLE
Expected behavior for state() and statenames() with matrix parameters?

### ISSUE THREAD

**Issue by joshday** [joshday/OnlineStats.jl#9]
- What should `state()` and `statenames()` return?  

I'm thinking `state()` should return `Vector{Any}` so that `state(o)[someinteger]` coincides with the value of `statenames(o)[someinteger]`

An example is for fitting a multivariate normal distribution where `mean(o.c)` is a Vector and `cov(o.c)` is a Matrix.

```julia

statenames(o::FitMvNormal) = [:μ, :Σ, :nobs]

state(o::FitMvNormal) = Any[mean(o.c), cov(o.c), o.n]
```

**Comment by tbreloff** [comment]
I agree with this. In fact this is exactly what I did for FLS, while returns a Vector{Any}[vector, float, int]
