### ISSUE TITLE
Behavior change of stats() and value()

### ISSUE THREAD

**Issue by ValdarT** [joshday/OnlineStats.jl#91]
In the latest release - v"0.12.0" - the structure of Series has changed and `stats(s))` and `value(s))` (where `s` is some `Series`) will output a `Tuple` instead of values results directly (as they used to).

Is this behavior change intentional?

If so, then the docstrings need to be updated. Currently the ones for distributions do not work anymore - for example `?FitBeta`:
```
using Distributions, OnlineStats
  y = rand(Beta(3, 5), 1000)
  s = Series(y, FitBeta())
  Beta(value(s)...)
```
The last line should now be `Beta(value(s)[1]...)` to work but it seems like this behavior change was unintentional?

**Comment by joshday** [comment]
Ah, I need to update the examples!

Before, Series could hold a Tuple of OnlineStats or a single OnlineStat.  There were some hacky things I didn't like about supporting both, so now Series only holds a Tuple.  

One thing I'm considering is an AbstractSeries type and then I can add a subtype which only holds a single OnlineStat.

**Comment by ValdarT** [comment]
But perhaps `stats()` and `value()` should still behave as they did before? At least in cases where it makes sense (like the distributions examples).

**Comment by joshday** [comment]
The distributions example doesn't change much:

```julia
using Distributions, OnlineStats
y = rand(Beta(3, 5), 1000)
o = FitBeta()
s = Series(y, o)
Beta(value(o)...)
```

I also don't think `value` should behave differently between these two:

```
Series(Mean())
Series(Mean(), Variance())
``` 

I think you can do more things programmatically with Series if `value` behavior is consistent.
