### ISSUE TITLE
How to compute Cov without Bessel’s correction ?

### ISSUE THREAD

**Issue by programistawpf** [joshday/OnlineStats.jl#97]
In base Julia  and in OnlineStats cov is computing with Bessel’s correction. 
If I want compute cov without can use corrected=false parametr. 
cov(v1[, v2][, vardim=1, corrected=false, mean=nothing])

How in OnlineStats to compute cov without Bessel’s correction ?
Paul

**Comment by joshday** [comment]
There isn't a way to turn off the correction currently.  Here is (not a very elegant) workaround:

```julia
julia> o = CovMatrix(3);

julia> s = Series(randn(100,3), o)
▦ Series{1}  |  EqualWeight  |  nobs = 100
└── CovMatrix([0.803161 0.00459935 0.117652; 0.00459935 0.726895 0.0020448; 0.117652 0.0020448 0.988639])

julia> (nobs(s) - 1) / nobs(s) * value(o)
3×3 Array{Float64,2}:
 0.795129    0.00455336  0.116476
 0.00455336  0.719626    0.00202435
 0.116476    0.00202435  0.978752
```

It would be an easy feature to add.

**Comment by programistawpf** [comment]
Thankas:) Yes.. I know :)
W dniu 2017-12-11 o 14:30, Josh Day pisze:
>
> There isn't a way to turn off the correction currently. Here is (not a 
> very elegant) workaround:
>
> julia>  o=  CovMatrix(3);
>
> julia>  s=  Series(randn(100,3), o)
> ▦ Series{1}|   EqualWeight|   nobs=  100
> └──CovMatrix([0.803161  0.00459935  0.117652;0.00459935  0.726895  0.0020448;0.117652  0.0020448  0.988639])
>
> julia>  (nobs(s)-  1)/  nobs(s)*  value(o)
> 3×3  Array{Float64,2}:
>   0.795129     0.00455336   0.116476
>   0.00455336   0.719626     0.00202435
>   0.116476     0.00202435   0.978752
>
> It would be an easy feature to add.
>
